small enhancements [Gerardo]
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@605 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1297,6 +1297,7 @@ libdirs=$LIBDIRS
 ar=$AR
 arflags=$ARFLAGS
 mylib=$MYLIB
+includefftw=$INCLUDEFFTW
 
 # configure for current directory by default
 if test "$topdir" = "" ; then topdir="`pwd`" ; fi
@@ -1402,7 +1403,6 @@ esac
 
 # check Fortran 90 compiler
 if test "$f90" = "" ; then f90="$try_f90" ; fi
-unset F77 # otherwise it may interfere with the check
 ac_ext=f
 ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -1803,8 +1803,8 @@ f90=$F77
 case "$build:$f90" in
 *-pc-linux-gnu:pgf* )
 	is_pgi=1
-	try_cc="pgcc gcc cc icc"
-	try_f77="pgf77 $f90"
+	try_cc="mpicc pgcc gcc cc icc"
+	try_f77="mpif77 pgf77 $f90"
 	;;
 *-pc-linux-gnu:ifort | *-pc-linux-*:ifc )
 	# extract compiler version
@@ -3001,6 +3001,7 @@ then
 	then
 		try_libdirs="/usr/local/lib
 			     /opt/intel/mkl/mkl61/lib/32 /opt/intel/mkl/lib/32
+			     /opt/intel/mkl61/lib/32
 			     /cineca/lib /cineca/prod/intel/lib"
 	elif test $is_linux && test $is_pgi
 	then
@@ -3503,6 +3504,99 @@ ac_compiler_gnu=$ac_cv_f77_compiler_gnu
 
 	if ! test $have_blas
 	then
+		# check for atlas (in several directories)
+		for dir in none $try_libdirs
+		do
+			unset ac_cv_search_dgemm # clear cached value
+			if test "$dir" = "none"
+			then
+				try_loption=
+			else
+				echo $ECHO_N "in $dir: " $ECHO_C
+				try_loption="-L$dir"
+			fi
+			FFLAGS="$test_fflags"
+			LDFLAGS="$test_ldflags $try_loption"
+			LIBS="$libs"
+			echo "$as_me:$LINENO: checking for library containing dgemm" >&5
+echo $ECHO_N "checking for library containing dgemm... $ECHO_C" >&6
+if test "${ac_cv_search_dgemm+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_dgemm=no
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call dgemm
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_dgemm="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search_dgemm" = no; then
+  for ac_lib in f77blas; do
+    LIBS="-l$ac_lib -latlas $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call dgemm
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_dgemm="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_dgemm" >&5
+echo "${ECHO_T}$ac_cv_search_dgemm" >&6
+if test "$ac_cv_search_dgemm" != no; then
+  test "$ac_cv_search_dgemm" = "none required" || LIBS="$ac_cv_search_dgemm $LIBS"
+  have_blas=1
+				       libs="$try_loption \
+$ac_cv_search_dgemm -latlas $libs"
+fi
+
+			if test "$ac_cv_search_dgemm" != "no"
+			then break ; fi
+		done
+	fi
+
+	if ! test $have_blas
+	then
 		# check for blas
 		FFLAGS="$test_fflags"
 		LDFLAGS="$test_ldflags"
@@ -3539,7 +3633,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 if test "$ac_cv_search_dgemm" = no; then
-  for ac_lib in atlas blas; do
+  for ac_lib in blas; do
     LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
     cat >conftest.$ac_ext <<_ACEOF
       program main
@@ -4232,16 +4326,25 @@ echo "$as_me:$LINENO: result: $ac_cv_search_fftwnd" >&5
 echo "${ECHO_T}$ac_cv_search_fftwnd" >&6
 if test "$ac_cv_search_fftwnd" != no; then
   test "$ac_cv_search_fftwnd" = "none required" || LIBS="$ac_cv_search_fftwnd $LIBS"
-  have_fft=1 want_fftw_h=1
+  have_fft=1 have_fftw=1
 fi
 
 fi
 
 # find location of fftw.h (if needed)
-if test $want_fftw_h
+if test $have_fftw
 then
-	includepath="/usr/local/include /cineca/lib/fftw-2.1.3/fftw"
-	for dir in none $includepath
+	if test "$includefftw" = ""
+	then
+		# if libfftw is in /some/path/lib, then fftw.h is
+		# likely to be in /some/path/include
+		includefftw=`echo $libs |
+			sed 's/.*-L\([^ ]*\)  *-lfftw.*/\1/
+			     s/lib/include/'`
+	fi
+	try_includedirs="$includefftw /usr/local/include \
+			 /cineca/lib/fftw-2.1.3/fftw"
+	for dir in none $try_includedirs
 	do
 		unset ac_cv_header_fftw_h # clear cached value
 		if test "$dir" = "none"
@@ -4624,8 +4727,7 @@ echo "${ECHO_T}$ac_cv_header_fftw_h" >&6
 
 fi
 if test $ac_cv_header_fftw_h = yes; then
-  unset want_fftw_h
-				ifftw="$try_ioption"
+  have_fftw_h=1 ifftw="$try_ioption"
 fi
 
 
@@ -4633,9 +4735,14 @@ fi
 	done
 fi
 
-if ! test $have_fft || test $want_fftw_h
+if test $have_fftw && ! test $have_fftw_h
 then
 	try_dflags="$try_dflags -D__USE_INTERNAL_FFTW"
+	if test $have_fft
+	then
+		{ echo "$as_me:$LINENO: WARNING: fftw library detected, but fftw.h not found" >&5
+echo "$as_me: WARNING: fftw library detected, but fftw.h not found" >&2;}
+	fi
 fi
 
 ac_ext=f
@@ -7767,20 +7874,26 @@ fi
 
 
 # final warnings
-echo -------------------------------------------------------------------
+echo -----------------------------------------------------------------
 echo PWscf can take advantage of several optimized numerical libraries
 echo \(essl, fftw, mkl...\).  This configure script attempts to find them,
 echo but may fail if they have been installed in non-standard locations.
 echo
 echo The following libraries have been found:
 echo "  LIBS=$libs"
+
+if test $have_fft && test $have_fftw && ! test $have_fftw_h
+then
+	echo "  WARNING: fftw library detected, but fftw.h not found"
+fi
+
 echo
 echo If any libraries are missing, you may specify a list of directories
 echo to search and retry, as follows:
 echo "  ./configure LIBDIRS=\"list of directories, separated by spaces\""
 echo
-echo \(For more information, read the INSTALL file or the PWscf manuals.\)
-echo -------------------------------------------------------------------
+echo For more information, read the INSTALL file or the PWscf manuals.
+echo -----------------------------------------------------------------
 
 if ! test $parallel
 then
