added support for Itanium/Intel compiler [Gerardo]
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@739 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1302,12 +1302,8 @@ includefftw=$INCLUDEFFTW
 # command-line arguments
 for arg in $*
 do
-	if test "$arg" = "--disable-parallel"
-	then
-		no_parallel=1
-	elif test "$arg" = "--disable-shared"
-	then
-		no_shared=1
+	if   test "$arg" = "--disable-parallel" ; then no_parallel=1
+	elif test "$arg" = "--disable-shared"   ; then no_shared=1
 	fi
 done
 
@@ -1375,7 +1371,15 @@ build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 # check compiling environment
 case $build in
-*-pc-linux-* )
+ia64-*-linux-gnu )
+	is_linux64=1
+	try_f90_parallel="mpif90"
+	try_f90="ifort ifc f90 f77 g77"
+	try_ar="ar"
+	try_arflags="ruv"
+	try_dflags="-D__LINUX64"
+	;;
+*-pc-linux-gnu )
 	is_linux=1
 	try_f90_parallel="mpif90"
 	try_f90="ifort ifc pgf90 f90 pgf77 f77 g77"
@@ -1518,7 +1522,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:1521:" \
+echo "$as_me:1525:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -1824,6 +1828,12 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 f90=$F77
 
 case "$build:$f90" in
+ia64-*-linux-gnu:ifort )
+	is_ifc=1
+	version=8
+	try_cc="icc gcc cc mpicc pgcc"
+	try_f77="$f90"
+	;;
 *-pc-linux-gnu:pgf* )
 	is_pgi=1
 	try_cc="pgcc gcc cc icc"
@@ -1988,7 +1998,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:1991:" \
+echo "$as_me:2001:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -2567,15 +2577,17 @@ cc=$CC
 # check whether the C and Fortran compilers are compatible
 case "$build:$cc:$f90" in
 	# list supported combinations here
-*-ibm-aix*:mpcc_r:mpxlf*_r | *-ibm-aix*:mpcc:mpxlf* | \
-*-ibm-aix*:xlc:*xlf* | *-ibm-aix*:cc:*xlf* )            ;;
-*-pc-linux-*:*cc:mpif90 )                               ;;
-*-pc-linux-*:pgcc:pgf90 )                               ;;
-*-pc-linux-*:icc:ifc | *-pc-linux-*:gcc:ifc | \
-*-pc-linux-*:icc:ifort | *-pc-linux-*:gcc:ifort )       ;;
-mips-sgi-*:cc:f90 )                                     ;;
-alphaev*-dec-osf*:cc:f90 )				;;
-# sparc-sun-*:mpcc:mpf90 | sparc-sun-*:cc:f90 )           ;;
+ia64-*-linux-gnu:icc:ifort )                          ;;
+ia64-*-linux-gnu:gcc:ifort )                          ;;
+*-pc-linux-gnu:*cc:mpif90 )                           ;;
+*-pc-linux-gnu:pgcc:pgf90 )                           ;;
+*-pc-linux-gnu:icc:ifc | *-pc-linux-*:icc:ifort )     ;;
+*-pc-linux-gnu:gcc:ifc | *-pc-linux-*:gcc:ifort )     ;;
+*-ibm-aix*:mpcc_r:mpxlf*_r | *-ibm-aix*:mpcc:mpxlf* ) ;;
+*-ibm-aix*:xlc:*xlf* | *-ibm-aix*:cc:*xlf* )          ;;
+mips-sgi-*:cc:f90 )                                   ;;
+alphaev*-dec-osf*:cc:f90 )                            ;;
+# sparc-sun-*:mpcc:mpf90 | sparc-sun-*:cc:f90 )         ;;
 
 * )
 	{ echo "$as_me:$LINENO: WARNING: unsupported C/Fortran compilers combination" >&5
@@ -2588,6 +2600,15 @@ esac
 
 # check compilers flags
 case "$build:$f90" in
+ia64-*-linux-gnu:ifort )
+	try_fflags="-Vaxlib -O2"
+	try_fflags_noopt="-O0"
+	try_ldflags="-Vaxlib"
+	try_ldflags_static="-static"
+	try_dflags="$try_dflags -D__INTEL"
+	pre_f_dflags="-fpp "
+	have_cpp=1
+	;;
 *-pc-linux-gnu:* )
 	if test $is_pgi
 	then
@@ -2700,7 +2721,11 @@ echo setting FFLAGS... $fflags
 echo setting F90FLAGS... $f90flags
 
 case "$build:$cc" in
-*-pc-linux-*:mpicc )
+ia64-*-linux-gnu:icc )
+	try_cflags="-O3"
+	c_ldflags="-Vaxlib"
+	;;
+*-pc-linux-gnu:mpicc )
 	if test $is_pgi
 	then
 		try_cflags="-fast"
@@ -2711,11 +2736,11 @@ case "$build:$cc" in
 		c_ldflags="-Vaxlib"
 	fi
 	;;
-*-pc-linux-*:pgcc )
+*-pc-linux-gnu:pgcc )
 	try_cflags="-fast"
 	c_ldflags=""
 	;;
-*-pc-linux-*:icc )
+*-pc-linux-gnu:icc )
 	try_cflags="-O3"
 	c_ldflags="-Vaxlib"
 	;;
@@ -3038,9 +3063,11 @@ F77=$f90 # use Fortran 90 actually (autoconf only knows Fortran 77!)
 if test "$libs" = ""
 then
 	# build list of directories to search
-	if test $is_aix
+	if test $is_linux64 && test $is_ifc
 	then
-		try_libdirs="/usr/local/lib /cineca/lib /cineca/lib/mass"
+		try_libdirs="/usr/local/lib
+			     /opt/intel/mkl/mkl61/lib/64 /opt/intel/mkl/lib/64
+			     /opt/intel/mkl61/lib/64"
 	elif test $is_linux && test $is_ifc
 	then
 		try_libdirs="/usr/local/lib
@@ -3053,6 +3080,9 @@ then
 			     /usr/local/pgi/linux86/lib
 			     /opt/pgi/linux86/5.1/lib
 			     /cineca/lib /cineca/prod/pgi/lib"
+	elif test $is_aix
+	then
+		try_libdirs="/usr/local/lib /cineca/lib /cineca/lib/mass"
 	elif test $is_mips
 	then
 		try_libdirs="/usr/local/lib /cineca/lib"
@@ -3075,7 +3105,190 @@ then
 	fi
 
 	# use vendor libraries if available
-	if test $is_aix
+	if test $is_linux64 && test $is_ifc
+	then
+		# check for mkl (in several directories)
+		for dir in none $try_libdirs
+		do
+			unset ac_cv_search_zggev # clear cached value
+			if test "$dir" = "none"
+			then
+				try_loption=
+			else
+				echo $ECHO_N "in $dir: " $ECHO_C
+				try_loption="-L$dir"
+			fi
+			FFLAGS="$test_fflags"
+			LDFLAGS="$test_ldflags $try_loption"
+			LIBS="$libs"
+
+echo "$as_me:$LINENO: checking for library containing zggev" >&5
+echo $ECHO_N "checking for library containing zggev... $ECHO_C" >&6
+if test "${ac_cv_search_zggev+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_zggev=no
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call zggev
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_zggev="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search_zggev" = no; then
+  for ac_lib in mkl_lapack; do
+    LIBS="-l$ac_lib -lmkl_ipf -lguide $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call zggev
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_zggev="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_zggev" >&5
+echo "${ECHO_T}$ac_cv_search_zggev" >&6
+if test "$ac_cv_search_zggev" != no; then
+  test "$ac_cv_search_zggev" = "none required" || LIBS="$ac_cv_search_zggev $LIBS"
+  have_blas=1 have_lapack=1
+				       libs="$try_loption \
+$ac_cv_search_zggev -lmkl_ipf -lguide $libs"
+fi
+
+			if test "$ac_cv_search_zggev" != "no"
+			then break ; fi
+		done
+	elif test $is_linux && test $is_ifc
+	then
+		# check for mkl (in several directories)
+		for dir in none $try_libdirs
+		do
+			unset ac_cv_search_zggev # clear cached value
+			if test "$dir" = "none"
+			then
+				try_loption=
+			else
+				echo $ECHO_N "in $dir: " $ECHO_C
+				try_loption="-L$dir"
+			fi
+			FFLAGS="$test_fflags"
+			LDFLAGS="$test_ldflags $try_loption"
+			LIBS="$libs"
+			echo "$as_me:$LINENO: checking for library containing zggev" >&5
+echo $ECHO_N "checking for library containing zggev... $ECHO_C" >&6
+if test "${ac_cv_search_zggev+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_zggev=no
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call zggev
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_zggev="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search_zggev" = no; then
+  for ac_lib in mkl_lapack; do
+    LIBS="-l$ac_lib -lmkl_ia32 -lguide $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call zggev
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_zggev="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_zggev" >&5
+echo "${ECHO_T}$ac_cv_search_zggev" >&6
+if test "$ac_cv_search_zggev" != no; then
+  test "$ac_cv_search_zggev" = "none required" || LIBS="$ac_cv_search_zggev $LIBS"
+  have_blas=1 have_lapack=1
+				       libs="$try_loption \
+$ac_cv_search_zggev -lmkl_ia32 -lguide $libs"
+fi
+
+			if test "$ac_cv_search_zggev" != "no"
+			then break ; fi
+		done
+	elif test $is_aix
 	then
 		# check for mass (in several directories)
 		for dir in none $try_libdirs
@@ -3091,8 +3304,7 @@ then
 			FFLAGS="$test_fflags"
 			LDFLAGS="$test_ldflags $try_loption"
 			LIBS="$libs"
-
-echo "$as_me:$LINENO: checking for library containing vexp" >&5
+			echo "$as_me:$LINENO: checking for library containing vexp" >&5
 echo $ECHO_N "checking for library containing vexp... $ECHO_C" >&6
 if test "${ac_cv_search_vexp+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3242,97 +3454,6 @@ if test "$ac_cv_search_dcft" != no; then
 			       libs="$LIBS"
 fi
 
-	elif test $is_linux && test $is_ifc
-	then
-		# check for mkl (in several directories)
-		for dir in none $try_libdirs
-		do
-			unset ac_cv_search_zggev # clear cached value
-			if test "$dir" = "none"
-			then
-				try_loption=
-			else
-				echo $ECHO_N "in $dir: " $ECHO_C
-				try_loption="-L$dir"
-			fi
-			FFLAGS="$test_fflags"
-			LDFLAGS="$test_ldflags $try_loption"
-			LIBS="$libs"
-			echo "$as_me:$LINENO: checking for library containing zggev" >&5
-echo $ECHO_N "checking for library containing zggev... $ECHO_C" >&6
-if test "${ac_cv_search_zggev+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_func_search_save_LIBS=$LIBS
-ac_cv_search_zggev=no
-cat >conftest.$ac_ext <<_ACEOF
-      program main
-      call zggev
-      end
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_search_zggev="none required"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-if test "$ac_cv_search_zggev" = no; then
-  for ac_lib in mkl_lapack; do
-    LIBS="-l$ac_lib -lmkl_ia32 -lguide $ac_func_search_save_LIBS"
-    cat >conftest.$ac_ext <<_ACEOF
-      program main
-      call zggev
-      end
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_search_zggev="-l$ac_lib"
-break
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-  done
-fi
-LIBS=$ac_func_search_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_search_zggev" >&5
-echo "${ECHO_T}$ac_cv_search_zggev" >&6
-if test "$ac_cv_search_zggev" != no; then
-  test "$ac_cv_search_zggev" = "none required" || LIBS="$ac_cv_search_zggev $LIBS"
-  have_blas=1 have_lapack=1
-				       libs="$try_loption \
-$ac_cv_search_zggev -lmkl_ia32 -lguide $libs"
-fi
-
-			if test "$ac_cv_search_zggev" != "no"
-			then break ; fi
-		done
 	elif test $is_mips
 	then
 		# check for complib.sgimath
