This may be the final version for 2.0 [Gerardo]
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@606 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3008,6 +3008,9 @@ then
 		try_libdirs="/usr/local/lib
 			     /usr/local/pgi/linux86/lib
 			     /cineca/lib /cineca/prod/pgi/lib"
+	elif test $is_mips
+	then
+		try_libdirs="/usr/local/lib /cineca/lib"
 	fi
 
 	# prepend directories specified by the user
@@ -3185,7 +3188,7 @@ echo "$as_me:$LINENO: result: $ac_cv_search_dcft" >&5
 echo "${ECHO_T}$ac_cv_search_dcft" >&6
 if test "$ac_cv_search_dcft" != no; then
   test "$ac_cv_search_dcft" = "none required" || LIBS="$ac_cv_search_dcft $LIBS"
-  have_fft=1 have_essl=1
+  have_fft=1 have_essl=1 have_blas=1
 			       libs="$LIBS"
 fi
 
@@ -4735,14 +4738,17 @@ fi
 	done
 fi
 
+# if no valid FFT library was found, use our implementation
+if ! test $have_fft
+then
+	try_dflags="$try_dflags -D__USE_INTERNAL_FFTW"
+fi
+
 if test $have_fftw && ! test $have_fftw_h
 then
 	try_dflags="$try_dflags -D__USE_INTERNAL_FFTW"
-	if test $have_fft
-	then
-		{ echo "$as_me:$LINENO: WARNING: fftw library detected, but fftw.h not found" >&5
+	{ echo "$as_me:$LINENO: WARNING: fftw library detected, but fftw.h not found" >&5
 echo "$as_me: WARNING: fftw library detected, but fftw.h not found" >&2;}
-	fi
 fi
 
 ac_ext=f
