examples deleted, environment_variables moved to main dir, all run_examples changed
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@8593 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/environment_variables b/environment_variables
--- a/environment_variables
+++ b/environment_variables
@@ -15,7 +15,7 @@
 
 # The following should be good in many cases 
 
-PREFIX=`cd ../.. ; pwd`
+PREFIX=`cd ../../.. ; pwd`
 BIN_DIR=$PREFIX/bin
 PSEUDO_DIR=$PREFIX/pseudo
 # Beware: everything in $TMP_DIR will be destroyed !
@@ -48,4 +48,16 @@ fi
 
 #PARA_PREFIX="mpirun -np 2"
 PARA_PREFIX=" "
-PARA_POSTFIX=
+PARA_POSTFIX=" "
+
+# function to test the exit status of a job
+check_failure () {
+    # usage: check_failure $?
+    if test $1 != 0
+    then
+        $ECHO "Error condition encountered during test: exit status = $1"
+        $ECHO "Aborting"
+        exit 1
+    fi
+}
+
