Added a check on the exit status of each job executed by the script using the function check_failure.
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@3854 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/examples/example01/run_example b/examples/example01/run_example
--- a/examples/example01/run_example
+++ b/examples/example01/run_example
@@ -7,13 +7,16 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
 $ECHO "This example shows how to use pw.x to calculate the total energy and"
 $ECHO "the band structure of four simple systems: Si, Al, Cu, Ni."
 
-# set the needed environment variables 
+# set the needed environment variables
 . ../environment_variables
 
 # required executables and pseudopotentials
@@ -28,7 +31,7 @@ $ECHO "  checking that needed directories and files exist...\c"
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
-    if test ! -d $DIR ; then 
+    if test ! -d $DIR ; then
         $ECHO
         $ECHO "ERROR: $DIR not existent or not a directory"
         $ECHO "Aborting"
@@ -89,21 +92,21 @@ for diago in david cg ; do
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =10.20, nat=  2, ntyp= 1,
-    ecutwfc =18.0, 
+    ecutwfc =18.0,
  /
  &electrons
     diagonalization='$diago'
     mixing_mode = 'plain'
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
     conv_thr =  1.0d-8
  /
 ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
- Si 0.00 0.00 0.00 
- Si 0.25 0.25 0.25 
+ Si 0.00 0.00 0.00
+ Si 0.25 0.25 0.25
 K_POINTS
   10
    0.1250000  0.1250000  0.1250000   1.00
@@ -119,6 +122,7 @@ K_POINTS
 EOF
     $ECHO "  running the scf calculation for Si...\c"
     $PW_COMMAND < si.scf.$diago.in > si.scf.$diago.out
+    check_failure $?
     $ECHO " done"
 
     # band structure calculation along delta, sigma and lambda lines
@@ -129,7 +133,7 @@ EOF
     outdir='$TMP_DIR/',
     prefix='silicon'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =10.20, nat=  2, ntyp= 1,
     ecutwfc =18.0, nbnd = 8,
  /
@@ -139,8 +143,8 @@ EOF
 ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
- Si 0.00 0.00 0.00 
- Si 0.25 0.25 0.25 
+ Si 0.00 0.00 0.00
+ Si 0.25 0.25 0.25
 K_POINTS
  28
    0.0 0.0 0.0 1.0
@@ -174,6 +178,7 @@ K_POINTS
 EOF
     $ECHO "  running the band-structure calculation for Si...\c"
     $PW_COMMAND < si.band.$diago.in > si.band.$diago.out
+    check_failure $?
     $ECHO " done"
 
 cat > si.bands.in << EOF
@@ -207,7 +212,7 @@ EOF
     tprnfor = .true.
     tstress = .true.
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =7.50, nat=  1, ntyp= 1, ecutwfc =15.0,
     occupations='smearing', smearing='marzari-vanderbilt', degauss=0.05
  /
@@ -218,7 +223,7 @@ EOF
 ATOMIC_SPECIES
  Al  26.98 Al.vbc.UPF
 ATOMIC_POSITIONS
- Al 0.00 0.00 0.00 
+ Al 0.00 0.00 0.00
 K_POINTS
   60
    0.0625000  0.0625000  0.0625000   1.00
@@ -284,6 +289,7 @@ K_POINTS
 EOF
     $ECHO "  running the scf calculation for Al...\c"
     $PW_COMMAND < al.scf.$diago.in > al.scf.$diago.out
+    check_failure $?
     $ECHO " done"
 
     # band structure calculation along delta, sigma and lambda lines
@@ -294,7 +300,7 @@ EOF
     outdir='$TMP_DIR/'
     prefix='al'
  /
- &system    
+ &system
     ibrav= 2, celldm(1) =7.50, nat=  1, ntyp= 1,
     ecutwfc =15.0, nbnd = 8
  /
@@ -304,7 +310,7 @@ EOF
 ATOMIC_SPECIES
  Al  26.98 Al.vbc.UPF
 ATOMIC_POSITIONS
- Al 0.00 0.00 0.00 
+ Al 0.00 0.00 0.00
 K_POINTS
  28
    0.0 0.0 0.0 1.0
@@ -338,6 +344,7 @@ K_POINTS
 EOF
     $ECHO "  running the band-structure calculation for Al...\c"
     $PW_COMMAND < al.band.$diago.in > al.band.$diago.out
+    check_failure $?
     $ECHO " done"
 
     # clean TMP_DIR
@@ -364,7 +371,7 @@ EOF
  &electrons
     diagonalization='$diago'
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Cu 63.55 Cu.pz-d-rrkjus.UPF
@@ -375,6 +382,7 @@ K_POINTS (automatic)
 EOF
     $ECHO "  running the scf calculation for Cu...\c"
     $PW_COMMAND < cu.scf.$diago.in > cu.scf.$diago.out
+    check_failure $?
     $ECHO " done"
 
     # band structure calculation along delta, sigma and lambda lines
@@ -429,6 +437,7 @@ K_POINTS
 EOF
     $ECHO "  running the band-structure calculation for Cu...\c"
     $PW_COMMAND < cu.band.$diago.in > cu.band.$diago.out
+    check_failure $?
     $ECHO " done"
 
 cat > cu.bands.in << EOF
@@ -472,7 +481,7 @@ EOF
  &electrons
     diagonalization='$diago'
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Ni 58.69 NiUS.RRKJ3.UPF
@@ -543,6 +552,7 @@ K_POINTS
 EOF
     $ECHO "  running the scf calculation for Ni...\c"
     $PW_COMMAND < ni.scf.$diago.in > ni.scf.$diago.out
+    check_failure $?
     $ECHO " done"
 
     # band structure calculation along delta, sigma and lambda lines
@@ -564,7 +574,7 @@ EOF
 ATOMIC_SPECIES
  Ni 58.69 NiUS.RRKJ3.UPF
 ATOMIC_POSITIONS
- Ni 0.0 0.0 0.0 
+ Ni 0.0 0.0 0.0
 K_POINTS
  28
    0.0 0.0 0.0 1.0
@@ -597,7 +607,8 @@ K_POINTS
    0.5 0.5 0.5 1.0
 EOF
     $ECHO "  running the band-structure calculation for Ni...\c"
-    $PW_COMMAND < ni.band.$diago.in > ni.band.$diago.out
+    $PW_COMMAND < ni.band.$diago.in > ni.band.$diago.out|
+    check_failure $?
     $ECHO " done"
 done
 
diff --git a/examples/example02/run_example b/examples/example02/run_example
--- a/examples/example02/run_example
+++ b/examples/example02/run_example
@@ -6,7 +6,10 @@ EXAMPLE_DIR=`pwd`
 
 # check whether ECHO has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -53,7 +56,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -87,7 +90,7 @@ cat > si.scf.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav = 2, celldm(1) =10.20, nat=  2, ntyp= 1,
     ecutwfc = 18.0
  /
@@ -98,8 +101,8 @@ cat > si.scf.in << EOF
 ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
- Si 0.00 0.00 0.00 
- Si 0.25 0.25 0.25 
+ Si 0.00 0.00 0.00
+ Si 0.25 0.25 0.25
 K_POINTS
   10
    0.1250000  0.1250000  0.1250000   1.00
@@ -115,6 +118,7 @@ K_POINTS
 EOF
 $ECHO "  running the scf calculation...\c"
 $PW_COMMAND < si.scf.in > si.scf.out
+check_failure $?
 $ECHO " done"
 
 # phonon calculation at Gamma
@@ -142,9 +146,9 @@ cat > si.nscfX.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =10.20, nat=  2, ntyp= 1,
-    ecutwfc =18.0, 
+    ecutwfc =18.0,
  /
  &electrons
     conv_thr =  1.0d-8
@@ -155,8 +159,8 @@ cat > si.nscfX.in << EOF
 ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
- Si 0.00 0.00 0.00 
- Si 0.25 0.25 0.25 
+ Si 0.00 0.00 0.00
+ Si 0.25 0.25 0.25
 K_POINTS
   10
    0.1250000  0.1250000  0.1250000   1.00
@@ -172,6 +176,7 @@ K_POINTS
 EOF
 $ECHO "  running the nscf calculation at X...\c"
 $PW_COMMAND < si.nscfX.in > si.nscfX.out
+check_failure $?
 $ECHO " done"
 
 # phonon calculation at X
@@ -188,6 +193,7 @@ phonons of si at X
 EOF
 $ECHO "  running the phonon calculation at X...\c"
 $PH_COMMAND < si.phX.in > si.phX.out
+check_failure $?
 $ECHO " done"
 
 # non self-consistent calculation at X for a single mode
@@ -198,9 +204,9 @@ cat > si.nscfXsingle.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =10.20, nat=  2, ntyp= 1,
-    ecutwfc =18.0, 
+    ecutwfc =18.0,
  /
  &electrons
     conv_thr =  1.0d-8
@@ -211,8 +217,8 @@ cat > si.nscfXsingle.in << EOF
 ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
- Si 0.00 0.00 0.00 
- Si 0.25 0.25 0.25 
+ Si 0.00 0.00 0.00
+ Si 0.25 0.25 0.25
 K_POINTS
   10
    0.1250000  0.1250000  0.1250000   1.00
@@ -228,6 +234,7 @@ K_POINTS
 EOF
 $ECHO "  running the nscf calculation at X for a single mode...\c"
 $PW_COMMAND < si.nscfXsingle.in > si.nscfXsingle.out
+check_failure $?
 $ECHO " done"
 
 # phonon calculation at X
@@ -243,6 +250,7 @@ phonons of si at X, single mode
 EOF
 $ECHO "  running the phonon calculation at X for a single mode...\c"
 $PH_COMMAND < si.phXsingle.in > si.phXsingle.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -259,7 +267,7 @@ cat > c.scf.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav = 2, celldm(1) =6.74, nat=  2, ntyp= 1,
     nr1=32,
     nr2=32,
@@ -274,13 +282,14 @@ cat > c.scf.in << EOF
 ATOMIC_SPECIES
  C   12.0107  C.pz-rrkjus.UPF
 ATOMIC_POSITIONS
- C  0.00 0.00 0.00 
- C  0.25 0.25 0.25 
+ C  0.00 0.00 0.00
+ C  0.25 0.25 0.25
 K_POINTS AUTOMATIC
 4 4 4 1 1 1
 EOF
 $ECHO "  running the scf calculation for C...\c"
 $PW_COMMAND < c.scf.in > c.scf.out
+check_failure $?
 $ECHO " done"
 
 # phonon calculation at G
@@ -298,6 +307,7 @@ phonons of C at Gamma
 EOF
 $ECHO "  running the phonon calculation at Gamma...\c"
 $PH_COMMAND < c.phG.in > c.phG.out
+check_failure $?
 $ECHO " done"
 
 
@@ -311,7 +321,7 @@ cat > ni.scf.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=2, celldm(1) =6.65, nat=  1, ntyp= 1,
     nspin=2,
     starting_magnetization(1)=0.5,
@@ -328,12 +338,13 @@ cat > ni.scf.in << EOF
 ATOMIC_SPECIES
  Ni  58.6934  Ni.pbe-nd-rrkjus.UPF
 ATOMIC_POSITIONS
- Ni 0.00 0.00 0.00 
+ Ni 0.00 0.00 0.00
 K_POINTS AUTOMATIC
 4 4 4 1 1 1
 EOF
 $ECHO "  running the scf calculation for Ni...\c"
 $PW_COMMAND < ni.scf.in > ni.scf.out
+check_failure $?
 $ECHO " done"
 
 # non self-consistent calculation for phonon at X of Ni with US-PP
@@ -346,7 +357,7 @@ cat > ni.nscf.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =6.65, nat=  1, ntyp= 1,
     nspin=2,
     starting_magnetization(1)=0.5,
@@ -366,12 +377,13 @@ cat > ni.nscf.in << EOF
 ATOMIC_SPECIES
  Ni  58.6934  Ni.pbe-nd-rrkjus.UPF
 ATOMIC_POSITIONS
- Ni 0.00 0.00 0.00 
+ Ni 0.00 0.00 0.00
 K_POINTS AUTOMATIC
 4 4 4 1 1 1
 EOF
 $ECHO "  running the non-scf calculation for phonon at X of Ni...\c"
 $PW_COMMAND < ni.nscf.in > ni.nscf.out
+check_failure $?
 $ECHO " done"
 
 # phonon calculation at X
@@ -388,6 +400,7 @@ phonons of Ni at X
 EOF
 $ECHO "  running the phonon calculation at X...\c"
 $PH_COMMAND < ni.phX.in > ni.phX.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
diff --git a/examples/example03/run_example b/examples/example03/run_example
--- a/examples/example03/run_example
+++ b/examples/example03/run_example
@@ -6,7 +6,10 @@ EXAMPLE_DIR=`pwd`
 
 # check whether ECHO has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -55,7 +58,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -88,9 +91,9 @@ cat > co.rx.in << EOF
 /
 &SYSTEM
   ibrav     = 0,
-  nat       = 2, 
+  nat       = 2,
   ntyp      = 2,
-  ecutwfc   = 24.D0, 
+  ecutwfc   = 24.D0,
   ecutrho   = 144.D0,
 /
 &ELECTRONS
@@ -110,11 +113,12 @@ O  1.00  O.LDA.US.RRKJ3.UPF
 C  1.00  C.pz-rrkjus.UPF
 ATOMIC_POSITIONS {bohr}
 C  2.256  0.0  0.0
-O  0.000  0.0  0.0  0 0 0 
+O  0.000  0.0  0.0  0 0 0
 K_POINTS {Gamma}
 EOF
 $ECHO "  running the geometry relaxation for CO...\c"
 $PW_COMMAND < co.rx.in > co.rx.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -130,9 +134,9 @@ cat > al001.rx.in << EOF
   outdir      = "$TMP_DIR",
 /
 &SYSTEM
-  ibrav       = 6, 
+  ibrav       = 6,
   celldm(1)   = 5.3033D0,
-  celldm(3)   = 8.D0, 
+  celldm(3)   = 8.D0,
   nat         = 7,
   ntyp        = 1,
   ecutwfc     = 12.D0,
@@ -167,6 +171,7 @@ K_POINTS
 EOF
 $ECHO "  running the geometry relaxation for Al (001) using BFGS...\c"
 $PW_COMMAND < al001.rx.in > al001.rx.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -175,7 +180,7 @@ rm -rf $TMP_DIR/*
 $ECHO " done"
 
 # self-consistent calculation
-rm -f e eal ave p avec tv 
+rm -f e eal ave p avec tv
 cat > al001.mm.in << EOF
 &CONTROL
   calculation = "relax",
@@ -184,9 +189,9 @@ cat > al001.mm.in << EOF
   outdir      = "$TMP_DIR",
 /
 &SYSTEM
-  ibrav       = 6, 
+  ibrav       = 6,
   celldm(1)   = 5.3033D0,
-  celldm(3)   = 8.D0, 
+  celldm(3)   = 8.D0,
   nat         = 7,
   ntyp        = 1,
   ecutwfc     = 12.D0,
@@ -221,6 +226,7 @@ K_POINTS
 EOF
 $ECHO "  running the geometry relaxation for Al (001) using damped MD...\c"
 $PW_COMMAND < al001.mm.in > al001.mm.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example04/run_example b/examples/example04/run_example
--- a/examples/example04/run_example
+++ b/examples/example04/run_example
@@ -7,6 +7,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -51,7 +54,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -101,12 +104,13 @@ ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
  Si -0.123 -0.123 -0.123
- Si  0.123  0.123  0.123 
+ Si  0.123  0.123  0.123
 K_POINTS {automatic}
  1 1 1 0 0 0
 EOF
 $ECHO "  running the MD calculation for Si in a 2 atom cell. G-point...\c"
 $PW_COMMAND < si.md2.in > si.md2.out
+check_failure $?
 $ECHO " done"
 
 awk '/Ekin/{ek=$3;et=$11; print it,time,ek,u,et}/Dynamics/{it=$5;time=$8}/^\!/{u=$5}' si.md2.out > MD2
@@ -155,6 +159,7 @@ K_POINTS {automatic}
 EOF
 $ECHO "  running the MD calculation for Si in a 8 atom cell. G-point...\c"
 $PW_COMMAND < si.md8.in > si.md8.out
+check_failure $?
 $ECHO " done"
 
 awk '/Ekin/{ek=$3;et=$11; print it,time,ek,u,et}/Dynamics/{it=$5;time=$8}/^\!/{u=$5}' si.md8.out > MD8
@@ -191,7 +196,7 @@ ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
  Si -0.123 -0.123 -0.123
- Si  0.123  0.123  0.123 
+ Si  0.123  0.123  0.123
 K_POINTS
  4
  0.0 0.0 0.0 1.0
@@ -201,9 +206,11 @@ K_POINTS
 EOF
 $ECHO "  running the MD calculation for Si in a 2 atom cell. G3X-points...\c"
 $PW_COMMAND < si.md2_G3X.in > si.md2_G3X.out
+check_failure $?
 $ECHO " done"
 
-awk '/Ekin/{ek=$3;et=$11; print it,time,ek,u,et}/Dynamics/{it=$5;time=$8}/^\!/{u=$5}' si.md2_G3X.out > MD2_G3X
+awk '/Ekin/{ek=$3;et=$11; print it,time,ek,u,et} \
+     /Dynamics/{it=$5;time=$8}/^\!/{u=$5}' si.md2_G3X.out > MD2_G3X
 
 $ECHO
 $ECHO "$EXAMPLE_DIR: done"
diff --git a/examples/example06/run_example b/examples/example06/run_example
--- a/examples/example06/run_example
+++ b/examples/example06/run_example
@@ -7,6 +7,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -51,7 +54,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -74,7 +77,7 @@ $ECHO "  running ph.x as:     $PH_COMMAND"
 $ECHO "  running q2r.x as:    $Q2R_COMMAND"
 $ECHO "  running matdyn.x as: $MATDYN_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -91,7 +94,7 @@ cat > alas.scf.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =10.50, nat=  2, ntyp= 2,
     ecutwfc =16.0
  /
@@ -103,8 +106,8 @@ ATOMIC_SPECIES
  Al  26.98  Al.vbc.UPF
  As  74.92  As.gon.UPF
 ATOMIC_POSITIONS
- Al 0.00 0.00 0.00 
- As 0.25 0.25 0.25 
+ Al 0.00 0.00 0.00
+ As 0.25 0.25 0.25
 K_POINTS
  2
  0.25 0.25 0.25 1.0
@@ -112,11 +115,12 @@ K_POINTS
 EOF
 $ECHO "  running the scf calculation...\c"
 $PW_COMMAND < alas.scf.in > alas.scf.out
+check_failure $?
 $ECHO " done"
 
 # phonon calculation on a (444) uniform grid of q-points
 cat > alas.ph.in << EOF
-phonons of AlAs 
+phonons of AlAs
  &inputph
   tr2_ph=1.0d-12,
   prefix='alas',
@@ -130,6 +134,7 @@ phonons of AlAs
 EOF
 $ECHO "  running the phonon calculation ...\c"
 $PH_COMMAND < alas.ph.in > alas.ph.out
+check_failure $?
 $ECHO " done"
 
 cat > q2r.in <<EOF
@@ -140,38 +145,41 @@ EOF
 
 $ECHO "  transforming C(q) => C(R)...\c"
 $Q2R_COMMAND < q2r.in > q2r.out
+check_failure $?
 $ECHO " done"
 
 cat > matdyn.in <<EOF
  &input
-    asr='simple',  amass(1)=26.98, amass(2)=74.922, 
+    asr='simple',  amass(1)=26.98, amass(2)=74.922,
     flfrc='alas444.fc', flfrq='alas.freq'
  /
  9
-  0.000 0.0 0.0  0.0 
-  0.125 0.0 0.0  0.0  
-  0.250 0.0 0.0  0.0  
-  0.375 0.0 0.0  0.0  
-  0.500 0.0 0.0  0.0  
-  0.625 0.0 0.0  0.0  
-  0.750 0.0 0.0  0.0  
-  0.875 0.0 0.0  0.0  
-  1.000 0.0 0.0  0.0  
+  0.000 0.0 0.0  0.0
+  0.125 0.0 0.0  0.0
+  0.250 0.0 0.0  0.0
+  0.375 0.0 0.0  0.0
+  0.500 0.0 0.0  0.0
+  0.625 0.0 0.0  0.0
+  0.750 0.0 0.0  0.0
+  0.875 0.0 0.0  0.0
+  1.000 0.0 0.0  0.0
 EOF
 
 $ECHO "  recalculating omega(q) from C(R)...\c"
 $MATDYN_COMMAND < matdyn.in > matdyn.out
+check_failure $?
 $ECHO " done"
 
 cat > phdos.in <<EOF
  &input
-    asr='simple',  dos=.true. amass(1)=26.98, amass(2)=74.922, 
+    asr='simple',  dos=.true. amass(1)=26.98, amass(2)=74.922,
     flfrc='alas444.fc', fldos='alas.phdos', nk1=6,nk2=6,nk3=6
  /
 EOF
 
 $ECHO "  calculating phonon DOS ...\c"
 $MATDYN_COMMAND < phdos.in > phdos.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example07/run_example b/examples/example07/run_example
--- a/examples/example07/run_example
+++ b/examples/example07/run_example
@@ -1,4 +1,11 @@
 #!/bin/sh
+
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
@@ -6,13 +13,16 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
 $ECHO "This example shows how to calculate electron-phonon interaction"
 $ECHO "coefficients for fcc Al."
 
-# set the needed environment variables 
+# set the needed environment variables
 . ../environment_variables
 # required executables and pseudopotentials
 BIN_LIST="pw.x ph.x q2r.x matdyn.x"
@@ -54,7 +64,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -84,7 +94,7 @@ rm -rf $TMP_DIR/*
 $ECHO "  done"
 
 #
-# SCF at dense k-mesh, good enough for electronic DOS  
+# SCF at dense k-mesh, good enough for electronic DOS
 #
 cat > al.scf.fit.in << EOF
  &control
@@ -96,9 +106,9 @@ cat > al.scf.fit.in << EOF
  /
  &system
     ibrav=  2, celldm(1) =7.5, nat= 1, ntyp= 1,
-    ecutwfc =15.0,   
+    ecutwfc =15.0,
     occupations='smearing', smearing='methfessel-paxton', degauss=0.05,
-    la2F = .true., 
+    la2F = .true.,
  /
  &electrons
     conv_thr =  1.0d-8
@@ -107,12 +117,13 @@ cat > al.scf.fit.in << EOF
 ATOMIC_SPECIES
  Al  26.98 Al.vbc.UPF
 ATOMIC_POSITIONS
- Al 0.00 0.00 0.00 
+ Al 0.00 0.00 0.00
 K_POINTS {automatic}
  16 16 16  0 0 0
 EOF
 $ECHO "  running the scf calculation with dense k-point grid...\c"
 $PW_COMMAND  < al.scf.fit.in > al.scf.fit.out
+check_failure $?
 $ECHO "  done"
 #
 #  SCF at k-mesh good enough for phonons
@@ -127,7 +138,7 @@ cat > al.scf.in << EOF
  /
  &system
     ibrav=  2, celldm(1) =7.5, nat= 1, ntyp= 1,
-    ecutwfc =15.0, 
+    ecutwfc =15.0,
     occupations='smearing', smearing='methfessel-paxton', degauss=0.05
  /
  &electrons
@@ -137,12 +148,13 @@ cat > al.scf.in << EOF
 ATOMIC_SPECIES
  Al  26.98 Al.vbc.UPF
 ATOMIC_POSITIONS
- Al 0.00 0.00 0.00 
+ Al 0.00 0.00 0.00
 K_POINTS {automatic}
  8 8 8  0 0 0
 EOF
 $ECHO "  running the scf calculation...\c"
 $PW_COMMAND < al.scf.in > al.scf.out
+check_failure $?
 $ECHO "  done"
 #
 cat > al.elph.in << EOF
@@ -162,25 +174,27 @@ Electron-phonon coefficients for Al
 EOF
 $ECHO "  running the el-ph calculation...\c"
 $PH_COMMAND < al.elph.in > al.elph.out
+check_failure $?
 $ECHO "  done"
 #
 #   q2r and matdyn
 #
-cat > q2r.in << EOF 
+cat > q2r.in << EOF
  &input
   zasr='simple',  fildyn='al.dyn', flfrc='Al444.fc', la2F=.true.
  /
 EOF
 $ECHO "  running q2r...\c"
 $Q2R_COMMAND < q2r.in > q2r.out
+check_failure $?
 $ECHO "  done"
 #
 #
 #
-cat > matdyn.in.freq << EOF 
+cat > matdyn.in.freq << EOF
  &input
     asr='simple',  amass(1)=26.98,
-    flfrc='Al444.fc', flfrq='Al444.freq', la2F=.true., dos=.false. 
+    flfrc='Al444.fc', flfrq='Al444.freq', la2F=.true., dos=.false.
  /
   19
   0.000 0.0 0.0     0.0
@@ -205,19 +219,21 @@ cat > matdyn.in.freq << EOF
 EOF
 $ECHO "  running matdyn for frequency calculation...\c"
 $MATDYN_COMMAND < matdyn.in.freq > matdyn.out.freq
+check_failure $?
 $ECHO "  done"
 #
 #
 #
-cat > matdyn.in.dos << EOF 
+cat > matdyn.in.dos << EOF
  &input
     asr='simple',  amass(1)=26.98,
-    flfrc='Al444.fc', flfrq='Al444.freq', la2F=.true., dos=.true. 
+    flfrc='Al444.fc', flfrq='Al444.freq', la2F=.true., dos=.true.
     fldos='phonon.dos', nk1=10, nk2=10, nk3=10, ndos=50
  /
 EOF
 $ECHO "  running matdyn for a2F(omega) calculation...\c"
 $MATDYN_COMMAND < matdyn.in.dos > matdyn.out.dos
+check_failure $?
 $ECHO "  done"
 
 
diff --git a/examples/example08/run_example b/examples/example08/run_example
--- a/examples/example08/run_example
+++ b/examples/example08/run_example
@@ -7,6 +7,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -50,7 +53,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -75,7 +78,7 @@ $ECHO "  running projwfc.x as: $PROJWFC_COMMAND"
 $ECHO "  running kvecs_FS.x as:  $KVECS_COMMAND"
 $ECHO "  running bands_FS.x as:  $BANDS_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -98,7 +101,7 @@ cat > ni.scf.in << EOF
  /
  &electrons
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Ni 58.69 NiUS.RRKJ3.UPF
@@ -169,6 +172,7 @@ K_POINTS
 EOF
 $ECHO "  running the scf calculation for Ni...\c"
 $PW_COMMAND < ni.scf.in > ni.scf.out
+check_failure $?
 $ECHO " done"
 
 # DOS calculation for Ni
@@ -187,7 +191,7 @@ cat > ni.dos.in << EOF
  /
  &electrons
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Ni 58.69 NiUS.RRKJ3.UPF
@@ -208,7 +212,9 @@ EOF
 
 $ECHO "  running DOS calculation for Ni...\c"
 $PW_COMMAND < ni.dos.in > ni.dos.out
+check_failure $?
 $DOS_COMMAND < ni.dos2.in > ni.dos2.out
+check_failure $?
 $ECHO " done"
 
 cat > ni.pdos.in << EOF
@@ -221,6 +227,7 @@ cat > ni.pdos.in << EOF
 EOF
 $ECHO "  running PDOS calculation for Ni...\c"
 $PROJWFC_COMMAND < ni.pdos.in > ni.pdos.out
+check_failure $?
 $ECHO " done"
 
 $ECHO "  Fermi Surface plot ...\c"
@@ -241,17 +248,18 @@ cat > ni.scf.in << EOF
  /
  &electrons
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Ni 58.69 NiUS.RRKJ3.UPF
 ATOMIC_POSITIONS
  Ni 0.0 0.0 0.0
 K_POINTS {automatic}
- 8 8 8 0 0 0 
+ 8 8 8 0 0 0
 EOF
 $ECHO "  running the scf calculation (no spin) ... \c"
 $PW_COMMAND < ni.scf.in > ni.scf0.out
+check_failure $?
 $ECHO " done"
 
 #
@@ -263,7 +271,7 @@ nabc=' 12 12 12 '
 n_start=3
 n_last=6
 #
-E_Fermi=`grep Fermi ni.scf0.out | cut -c 26-36` 
+E_Fermi=`grep Fermi ni.scf0.out | cut -c 26-36`
 a1=`grep 'b(1)' ni.scf.out | cut -c 24-54`
 a2=`grep 'b(2)' ni.scf.out | cut -c 24-54`
 a3=`grep 'b(3)' ni.scf.out | cut -c 24-54`
@@ -277,6 +285,7 @@ $Sysname
 EOF
 
 $KVECS_COMMAND < kvecs_FS.in > kvecs_FS.out
+check_failure $?
 
 cat > ni.fs.in << EOF
  &control
@@ -291,7 +300,7 @@ cat > ni.fs.in << EOF
  /
  &electrons
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Ni 58.69 NiUS.RRKJ3.UPF
@@ -304,7 +313,8 @@ cat  kvecs_$Sysname >> ni.fs.in
 
 # input file ni.fs.in ready
 $ECHO "  running the Fermi Surface calculation ... \c"
-$PW_COMMAND   < ni.fs.in > ni.fs.out 
+$PW_COMMAND   < ni.fs.in > ni.fs.out
+check_failure $?
 $ECHO " done"
 
 # prepare input data (input_FS, Bands.out) for bands_FS
@@ -323,7 +333,8 @@ $a3
 EOF
 
 $BANDS_COMMAND > bands_fs.out
-mv Bands.bxsf  ni.fs.bxsf 
+check_failure $?
+mv Bands.bxsf  ni.fs.bxsf
 
 $ECHO "  Fermi surface plot: use 'xcrysden --bxsf ni.fs.bxsf' to plot ...\c"
 $ECHO " done"
diff --git a/examples/example09/run_example b/examples/example09/run_example
--- a/examples/example09/run_example
+++ b/examples/example09/run_example
@@ -1,11 +1,20 @@
 #!/bin/sh
 
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
+
+# function to test the exit status of a job
+. ../check_failure.sh
 
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
@@ -53,7 +62,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -76,7 +85,7 @@ $ECHO "  running ph.x     as: $PH_COMMAND"
 $ECHO "  running phcg.x   as: $PHCG_COMMAND"
 $ECHO "  running dynmat.x as: $DYNMAT_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -114,6 +123,7 @@ K_POINTS (gamma)
 EOF
 $ECHO "  running the scf calculation for SiH4...\c"
 $PW_COMMAND < sih4.scf.in > sih4.scf.out
+check_failure $?
 $ECHO " done"
 
 # normal mode calculation for SiH4
@@ -124,7 +134,7 @@ normal modes for sih4
   prefix='sih4',
   amass(1)=28.086,
   amass(2)=1.008,
-  outdir='$TMP_DIR/', 
+  outdir='$TMP_DIR/',
   epsil=.true.,
   trans=.true., asr=.true.
   raman=.false.
@@ -134,6 +144,7 @@ normal modes for sih4
 EOF
 $ECHO "  running normal mode calculation for SiH4...\c"
 $PHCG_COMMAND < sih4.nm.in > sih4.nm.out
+check_failure $?
 $ECHO " done"
 
 # IR cross sections  for SiH4
@@ -143,6 +154,7 @@ EOF
 
 $ECHO "  running IR cross section calculation for SiH4...\c"
 $DYNMAT_COMMAND < sih4.dyn.in > sih4.dyn.out
+check_failure $?
 $ECHO " done"
 
 # Self consistent calculation for CH4
@@ -157,16 +169,16 @@ ch4 molecule in a cubic box
     pseudo_dir = '$PSEUDO_DIR',
     outdir='$TMP_DIR'
  /
- &system    
-    ibrav=  1, 
-    celldm(1) =15.0, 
-    nat=5, 
+ &system
+    ibrav=  1,
+    celldm(1) =15.0,
+    nat=5,
     ntyp= 2,
-    ecutwfc =25.0, 
-    ecutrho =100.0, 
+    ecutwfc =25.0,
+    ecutrho =100.0,
  /
  &electrons
-    mixing_beta = 0.5, 
+    mixing_beta = 0.5,
     conv_thr =  1.0d-8
  /
 ATOMIC_SPECIES
@@ -184,6 +196,7 @@ K_POINTS
 EOF
 $ECHO "  running the scf calculation for CH4...\c"
 $PW_COMMAND < ch4.scf.in > ch4.scf.out
+check_failure $?
 $ECHO " done"
 
 # normal mode calculation for CH4
@@ -203,8 +216,8 @@ vibrations of ch4
 EOF
 $ECHO "  running normal mode calculation for CH4...\c"
 $PH_COMMAND < ch4.nm.in > ch4.nm.out
+check_failure $?
 $ECHO " done"
-
 
 $ECHO
 $ECHO "$EXAMPLE_DIR: done"
diff --git a/examples/example10/run_example b/examples/example10/run_example
--- a/examples/example10/run_example
+++ b/examples/example10/run_example
@@ -7,6 +7,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -51,7 +54,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -68,7 +71,7 @@ PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
 $ECHO
 $ECHO "  running pw.x as: $PW_COMMAND"
 $ECHO
-                                                                                
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -101,16 +104,17 @@ ATOMIC_SPECIES
   Ti    47.867    Ti.vdb.UPF
   O     15.9994   O.vdb.UPF
 ATOMIC_POSITIONS
-  Pb    0.000    0.000    0.010 
-  Ti    0.500    0.500    0.500 
-  O     0.000    0.500    0.500 
-  O     0.500    0.500    0.000 
-  O     0.500    0.000    0.500 
+  Pb    0.000    0.000    0.010
+  Ti    0.500    0.500    0.500
+  O     0.000    0.500    0.500
+  O     0.500    0.500    0.000
+  O     0.500    0.000    0.500
 K_POINTS {automatic}
   4 4 4 1 1 1
 EOF
 $ECHO "  running self-consistent calculation in PbTiO3...\c"
 $PW_COMMAND < chg.in > chg.out
+check_failure $?
 $ECHO " done"
 
 # Berry Phase calculation
@@ -142,16 +146,17 @@ ATOMIC_SPECIES
   Ti    47.867    Ti.vdb.UPF
   O     15.9994   O.vdb.UPF
 ATOMIC_POSITIONS
-  Pb    0.000    0.000    0.010 
-  Ti    0.500    0.500    0.500 
-  O     0.000    0.500    0.500 
-  O     0.500    0.500    0.000 
-  O     0.500    0.000    0.500 
+  Pb    0.000    0.000    0.010
+  Ti    0.500    0.500    0.500
+  O     0.000    0.500    0.500
+  O     0.500    0.500    0.000
+  O     0.500    0.000    0.500
 K_POINTS {automatic}
   4 4 7  1 1 1
 EOF
 $ECHO "  running Berry Phase calculation for PbTiO3...\c"
 $PW_COMMAND < BP.in > BP.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example11/run_example b/examples/example11/run_example
--- a/examples/example11/run_example
+++ b/examples/example11/run_example
@@ -7,6 +7,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -52,7 +55,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -69,7 +72,7 @@ PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
 $ECHO
 $ECHO "  running pw.x as: $PW_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -99,15 +102,16 @@ cat > al.in << EOF
  /
 ATOMIC_SPECIES
 Al     26.98154    Al.vbc.UPF
-ATOMIC_POSITIONS   
+ATOMIC_POSITIONS
 Al      0.0000000000   0.0000000000     0.000
 K_POINTS  AUTOMATIC
 1   1   1   0   0   0
 OCCUPATIONS
-2.0 0.3333333333333 0.333333333333 0.3333333333333 0.0 0.0 
+2.0 0.3333333333333 0.333333333333 0.3333333333333 0.0 0.0
 EOF
 $ECHO "  running self-consistent calculation for Al atom...\c"
 $PW_COMMAND < al.in > al.out
+check_failure $?
 $ECHO " done"
 
 # self consistent calculation for the spin polarized O atom
@@ -137,16 +141,17 @@ cat > O.in << EOF
  /
 ATOMIC_SPECIES
 O     15.99994   O.pbe-rrkjus.UPF
-ATOMIC_POSITIONS   
-O   0.000000000   0.000000000   0.000000000  
+ATOMIC_POSITIONS
+O   0.000000000   0.000000000   0.000000000
 K_POINTS AUTOMATIC
 1   1   1   0   0   0
 OCCUPATIONS
-1.0 1.0 1.0 1.0 0.0 0.0 
-1.0 0.33333333333 0.33333333333 0.33333333333 0.0 0.0 
+1.0 1.0 1.0 1.0 0.0 0.0
+1.0 0.33333333333 0.33333333333 0.33333333333 0.0 0.0
 EOF
 $ECHO "  running calculation for O atom...\c"
 $PW_COMMAND < O.in > O.out
+check_failure $?
 $ECHO " done"
 
 #
@@ -176,15 +181,16 @@ cat > O_gamma.in << EOF
  /
 ATOMIC_SPECIES
 O     15.99994   O.pbe-rrkjus.UPF
-ATOMIC_POSITIONS   
-O   0.000000000   0.000000000   0.000000000  
+ATOMIC_POSITIONS
+O   0.000000000   0.000000000   0.000000000
 K_POINTS (gamma)
 OCCUPATIONS
-1.0 1.0 1.0 1.0 0.0 0.0 
-1.0 0.33333333333 0.33333333333 0.33333333333 0.0 0.0 
+1.0 1.0 1.0 1.0 0.0 0.0
+1.0 0.33333333333 0.33333333333 0.33333333333 0.0 0.0
 EOF
 $ECHO "  running calculation for O atom, Gamma-only...\c"
 $PW_COMMAND < O_gamma.in > O_gamma.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example12/run_example b/examples/example12/run_example
--- a/examples/example12/run_example
+++ b/examples/example12/run_example
@@ -1,12 +1,21 @@
 #!/bin/sh
-                                                                                
+
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -52,7 +61,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -71,7 +80,7 @@ $ECHO
 $ECHO "  running pw.x as:     $PW_COMMAND"
 $ECHO "  running pwcond.x as: $PWCOND_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -87,14 +96,14 @@ cat > al.scf.in << EOF
     prefix='al'
  /
  &system
-    ibrav = 6, 
-    celldm(1) =5.3, 
-    celldm(3) =1.414, 
-    nat= 2, 
+    ibrav = 6,
+    celldm(1) =5.3,
+    celldm(3) =1.414,
+    nat= 2,
     ntyp= 1,
-    ecutwfc = 15.0, 
-    occupations='smearing', 
-    smearing='methfessel-paxton', 
+    ecutwfc = 15.0,
+    occupations='smearing',
+    smearing='methfessel-paxton',
     degauss=0.01
  /
  &electrons
@@ -102,24 +111,25 @@ cat > al.scf.in << EOF
     mixing_beta = 0.7
  /
 ATOMIC_SPECIES
- Al 26.98 Al.vbc.UPF 
+ Al 26.98 Al.vbc.UPF
 ATOMIC_POSITIONS
  Al 0. 0. 0.0
  Al 0.5 0.5 0.707
 K_POINTS (automatic)
- 4 4 4 1 1 1                
+ 4 4 4 1 1 1
 EOF
 $ECHO "  running the scf calculation for Al...\c"
-$PW_COMMAND < al.scf.in > al.scf.out 
+$PW_COMMAND < al.scf.in > al.scf.out
+check_failure $?
 $ECHO " done"
 
 # complex bands of Al along the 001 direction K_perp=0
 cat > al.cond.in << EOF
  &inputcond
-    outdir='$TMP_DIR/'     
+    outdir='$TMP_DIR/'
     prefixl='al'
     band_file ='bands.al'
-    ikind=0  
+    ikind=0
     energy0=10.d0
     denergy=-0.4d0
     ewind=1.d0
@@ -132,7 +142,8 @@ cat > al.cond.in << EOF
     60
 EOF
 $ECHO "  running pwcond.x to calculate the complex bands of Al...\c"
-$PWCOND_COMMAND < al.cond.in > al.cond.out 
+$PWCOND_COMMAND < al.cond.in > al.cond.out
+check_failure $?
 $ECHO " done"
 
 # self-consistent calculation for Al monatomic wire
@@ -145,15 +156,15 @@ cat > alwire.scf.in << EOF
     prefix='alw'
  /
  &system
-    ibrav = 6, 
-    celldm(1) =12.0, 
-    celldm(3) =0.375, 
-    nat= 1, 
+    ibrav = 6,
+    celldm(1) =12.0,
+    celldm(3) =0.375,
+    nat= 1,
     ntyp= 1,
-    nspin = 1,  
-    ecutwfc = 15.0, 
-    occupations='smearing', 
-    smearing='methfessel-paxton', 
+    nspin = 1,
+    ecutwfc = 15.0,
+    occupations='smearing',
+    smearing='methfessel-paxton',
     degauss=0.01
  /
  &electrons
@@ -161,39 +172,41 @@ cat > alwire.scf.in << EOF
     mixing_beta = 0.7
  /
 ATOMIC_SPECIES
- Al 26.98 Al.vbc.UPF 
+ Al 26.98 Al.vbc.UPF
 ATOMIC_POSITIONS
- Al 0.0 0.0 0.000 
+ Al 0.0 0.0 0.000
 K_POINTS (automatic)
- 1 1 15 0 0 0                
+ 1 1 15 0 0 0
 EOF
 $ECHO "  running the scf calculation for Al monatomic wire...\c"
-$PW_COMMAND < alwire.scf.in > alwire.scf.out 
+$PW_COMMAND < alwire.scf.in > alwire.scf.out
+check_failure $?
 $ECHO " done"
 
 # complex bands of the Al monatomic wire
 cat > alwire.cond.in << EOF
  &inputcond
-    outdir='$TMP_DIR/'     
+    outdir='$TMP_DIR/'
     prefixl='alw'
     band_file='bands.alwire'
-    ikind=0  
+    ikind=0
     energy0=7.0d0
     denergy=-0.2d0
     ewind=1.d0
     epsproj=1.d-3
     nz1=3
-    cutplot = 1.d0 
+    cutplot = 1.d0
  /
     1
-    0. 0. 1.0 
+    0. 0. 1.0
     71
 EOF
 $ECHO "  running pwcond.x to calculate the complex bands of Al wire...\c"
-$PWCOND_COMMAND < alwire.cond.in > alwire.cond.out 
+$PWCOND_COMMAND < alwire.cond.in > alwire.cond.out
+check_failure $?
 $ECHO " done"
 
-# self-consistent calculation for bulk Ni 
+# self-consistent calculation for bulk Ni
 cat > ni.scf.in << EOF
  &control
     calculation='scf'
@@ -203,17 +216,17 @@ cat > ni.scf.in << EOF
     prefix='ni'
  /
  &system
-    ibrav = 6, 
-    celldm(1) =4.57, 
-    celldm(3) =1.414, 
-    nat= 2, 
+    ibrav = 6,
+    celldm(1) =4.57,
+    celldm(3) =1.414,
+    nat= 2,
     ntyp= 1,
-    nspin = 2,  
+    nspin = 2,
     starting_magnetization(1)=0.7,
-    ecutwfc = 25.0, 
+    ecutwfc = 25.0,
     ecutrho = 250.0
-    occupations='smearing', 
-    smearing='methfessel-paxton', 
+    occupations='smearing',
+    smearing='methfessel-paxton',
     degauss=0.01
  /
  &electrons
@@ -221,24 +234,25 @@ cat > ni.scf.in << EOF
     mixing_beta = 0.7
  /
 ATOMIC_SPECIES
- Ni 58.69 NiUS.RRKJ3.UPF 
+ Ni 58.69 NiUS.RRKJ3.UPF
 ATOMIC_POSITIONS
- Ni 0. 0. 0. 
+ Ni 0. 0. 0.
  Ni 0.5 0.5 0.707
 K_POINTS (automatic)
- 4 4 3 1 1 1                
+ 4 4 3 1 1 1
 EOF
 $ECHO "  running the scf calculation for Ni bulk...\c"
-$PW_COMMAND < ni.scf.in > ni.scf.out 
+$PW_COMMAND < ni.scf.in > ni.scf.out
+check_failure $?
 $ECHO " done"
 
 # complex bands of Ni
 cat > ni.cond.in << EOF
  &inputcond
-    outdir='$TMP_DIR/'     
+    outdir='$TMP_DIR/'
     prefixl='ni'
     band_file = 'bands.ni_down'
-    ikind=0  
+    ikind=0
     iofspin = 2
     energy0=1.d0
     denergy=-0.2d0
@@ -251,7 +265,8 @@ cat > ni.cond.in << EOF
     30
 EOF
 $ECHO "  running pwcond.x to calculate the complex bands of Ni...\c"
-$PWCOND_COMMAND < ni.cond.in > ni.cond.out 
+$PWCOND_COMMAND < ni.cond.in > ni.cond.out
+check_failure $?
 $ECHO " done"
 
 # self-consistent calculation for Al monatomic wire
@@ -288,9 +303,9 @@ K_POINTS (automatic)
  2 2 24 1 1 1
 EOF
 $ECHO "  running the scf calculation for Al monatomic wire...\c"
-$PW_COMMAND < alwire1.scf.in > alwire1.scf.out 
+$PW_COMMAND < alwire1.scf.in > alwire1.scf.out
+check_failure $?
 $ECHO " done"
-
 
 # self-consistent calculation for  Al-H-Al system
 cat > AlwireH.scf.in << EOF
@@ -331,10 +346,11 @@ K_POINTS (automatic)
  2 2 2 1 1 1
 EOF
 $ECHO "  running the scf calculation for Al wire with H impurity...\c"
-$PW_COMMAND < AlwireH.scf.in > AlwireH.scf.out 
+$PW_COMMAND < AlwireH.scf.in > AlwireH.scf.out
+check_failure $?
 $ECHO " done"
 
-# transmission calculation for the perfect Al wire 
+# transmission calculation for the perfect Al wire
 cat > AlwireAl.cond.in << EOF
  &inputcond
     outdir='$TMP_DIR/',
@@ -353,7 +369,8 @@ cat > AlwireAl.cond.in << EOF
     100
 EOF
 $ECHO "  running pwcond.x to calculate transmission of a perfect Al wire ...\c"
-$PWCOND_COMMAND < AlwireAl.cond.in > AlwireAl.cond.out 
+$PWCOND_COMMAND < AlwireAl.cond.in > AlwireAl.cond.out
+check_failure $?
 $ECHO " done"
 
 # transmission calculation for the Al-C-Al
@@ -393,7 +410,8 @@ cat > AlwireH.cond.in << EOF
  -6.45
 EOF
 $ECHO "  running pwcond.x to calculate transmission of an Al wire with H...\c"
-$PWCOND_COMMAND < AlwireH.cond.in > AlwireH.cond.out 
+$PWCOND_COMMAND < AlwireH.cond.in > AlwireH.cond.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example13/run_example b/examples/example13/run_example
--- a/examples/example13/run_example
+++ b/examples/example13/run_example
@@ -1,12 +1,15 @@
 #!/bin/sh
-                                                                                
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -53,7 +56,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -70,7 +73,7 @@ PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
 $ECHO
 $ECHO "  running pw.x as: $PW_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -121,9 +124,10 @@ K_POINTS
 EOF
 $ECHO "  running the scf calculation for Fe...\c"
 $PW_COMMAND < fe.scf.in > fe.scf.out
+check_failure $?
 $ECHO " done"
 
-# band structure calculation 
+# band structure calculation
 cat > fe.band.in << EOF
 Fe
 Iron
@@ -183,6 +187,7 @@ K_POINTS
 EOF
 $ECHO "  running band structure calculation for Fe...\c"
 $PW_COMMAND < fe.band.in > fe.band.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -235,6 +240,7 @@ K_POINTS
 EOF
 $ECHO "  running scf calculation for Fe with penalty functional...\c"
 $PW_COMMAND < fe.pen.in > fe.pen.out
+check_failure $?
 $ECHO " done"
 
 # scf calculation with penalty functional (angle with z-axis constrained)
@@ -282,6 +288,7 @@ K_POINTS
 EOF
 $ECHO "  running the scf calculation for Fe with constrained angle...\c"
 $PW_COMMAND < fe.angl.in > fe.angl.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -326,6 +333,7 @@ K_POINTS AUTOMATIC
 EOF
 $ECHO "  running the scf calculation for Fe with constrained magnetization...\c"
 $PW_COMMAND < fe.total.in > fe.total.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -353,7 +361,7 @@ cat > cu.scf.in << EOF
  /
  &electrons
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Cu 63.55 Cu.pz-d-rrkjus.UPF
@@ -364,6 +372,7 @@ K_POINTS (automatic)
 EOF
 $ECHO "  running the scf calculation for Cu...\c"
 $PW_COMMAND < cu.scf.in > cu.scf.out
+check_failure $?
 $ECHO " done"
 
 # band structure calculation along delta, sigma and lambda lines
@@ -421,6 +430,7 @@ K_POINTS
 EOF
 $ECHO "  running the band-structure calculation for Cu...\c"
 $PW_COMMAND < cu.band.in > cu.band.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -460,6 +470,7 @@ K_POINTS (automatic)
 EOF
 $ECHO "  running the scf calculation for Cu with cg diagonalization...\c"
 $PW_COMMAND < cu.cg.in > cu.cg.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -467,7 +478,7 @@ $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
 $ECHO " done"
 
-# self-consistent calculation with diis diagonalization 
+# self-consistent calculation with diis diagonalization
 cat > cu.diis.in << EOF
  &control
     calculation='scf'
@@ -499,6 +510,7 @@ K_POINTS (automatic)
 EOF
 # $ECHO "  running the scf calculation for Cu with diis diagonalization...\c"
 # $PW_COMMAND < cu.diis.in > cu.diis.out
+# check_failure $?
 # $ECHO " done"
 
 # clean TMP_DIR
@@ -526,7 +538,7 @@ cat > ni.scf.in << EOF
  /
  &electrons
     conv_thr = 1.0e-8
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
  /
 ATOMIC_SPECIES
  Ni 58.69 Ni.pbe-nd-rrkjus.UPF
@@ -597,6 +609,7 @@ K_POINTS
 EOF
 $ECHO "  running the scf calculation for Ni...\c"
 $PW_COMMAND < ni.scf.in > ni.scf.out
+check_failure $?
 $ECHO " done"
 
 # band structure calculation along delta, sigma and lambda lines
@@ -622,7 +635,7 @@ cat > ni.band.in << EOF
 ATOMIC_SPECIES
  Ni 58.69 Ni.pbe-nd-rrkjus.UPF
 ATOMIC_POSITIONS
- Ni 0.0 0.0 0.0 
+ Ni 0.0 0.0 0.0
 K_POINTS
  28
    0.0 0.0 0.0 1.0
@@ -656,6 +669,7 @@ K_POINTS
 EOF
 $ECHO "  running the band-structure calculation for Ni...\c"
 $PW_COMMAND < ni.band.in > ni.band.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -691,8 +705,8 @@ cat > o2.relax.in << EOF
  &ions
  /
 ATOMIC_SPECIES
- O1 55.847 O.pbe-rrkjus.UPF  
- O2 55.847 O.pbe-rrkjus.UPF  
+ O1 55.847 O.pbe-rrkjus.UPF
+ O2 55.847 O.pbe-rrkjus.UPF
 ATOMIC_POSITIONS
  O1 0.0 0.0 0.0
  O2 0.20 0.20 0.20
@@ -702,6 +716,7 @@ K_POINTS
 EOF
 $ECHO "  running scf calculation with relax for oxygen molecule...\c"
 $PW_COMMAND < o2.relax.in > o2.relax.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example14/run_example b/examples/example14/run_example
--- a/examples/example14/run_example
+++ b/examples/example14/run_example
@@ -1,12 +1,21 @@
 #!/bin/sh
-                                                                                
+
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -51,7 +60,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -72,7 +81,7 @@ $ECHO "  running pw.x as: $PW_COMMAND"
 $ECHO "  running ph.x as: $PH_COMMAND"
 $ECHO "  running d3.x as: $D3_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -89,24 +98,25 @@ cat > si.scf.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =10.20, nat=  2, ntyp= 1,
-    ecutwfc =24.0, 
+    ecutwfc =24.0,
  /
  &electrons
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
     conv_thr =  1.0d-8
  /
 ATOMIC_SPECIES
  Si  28.086  Si.vbc.UPF
 ATOMIC_POSITIONS
- Si 0.00 0.00 0.00 
- Si 0.25 0.25 0.25 
+ Si 0.00 0.00 0.00
+ Si 0.25 0.25 0.25
 K_POINTS {automatic}
  4 4 4  1 1 1
 EOF
 $ECHO "  running the scf calculation for Si...\c"
 $PW_COMMAND < si.scf.in > si.scf.out
+check_failure $?
 $ECHO " done"
 
 # calculation of the dynamical matrix at Gamma
@@ -116,7 +126,7 @@ phonons of Si at Gamma
   tr2_ph=1.0d-12,
   prefix='si',
   epsil=.false.,
-  trans=.true., 
+  trans=.true.,
   zue=.false.,
   amass(1)=28.0855,
   amass(2)=28.0855,
@@ -128,13 +138,14 @@ phonons of Si at Gamma
 EOF
 $ECHO "  running the phonon calculation for Si at Gamma...\c"
 $PH_COMMAND < si.phG.in > si.phG.out
+check_failure $?
 $ECHO " done"
 
 # calculation of the anharmonic tensor at Gamma
 cat > si.d3G.in << EOF
 Anharm at Gamma
 &inputph
-   prefix = 'si', 
+   prefix = 'si',
    fildrho = 'si.drho_G',
    fild0rho = 'si.drho_G',
    amass(1) = 28.0855,
@@ -145,6 +156,7 @@ Anharm at Gamma
 EOF
 $ECHO "  running the calculation of D3(0,0,0)...\c"
 $D3_COMMAND < si.d3G.in > si.d3G.out
+check_failure $?
 $ECHO " done"
 
 # NSCF calculation for the X-point phonon calculation
@@ -158,7 +170,7 @@ cat > si.nscf.in << EOF
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     nosym = .false.,
     ibrav=  2, celldm(1) =10.20, nat=  2, ntyp= 1,
     ecutwfc =24.0
@@ -173,13 +185,14 @@ cat > si.nscf.in << EOF
 ATOMIC_SPECIES
  Si  28.0855  Si.vbc.UPF
 ATOMIC_POSITIONS
- Si 0.00 0.00 0.00 
- Si 0.25 0.25 0.25 
+ Si 0.00 0.00 0.00
+ Si 0.25 0.25 0.25
 K_POINTS {automatic}
  4 4 4 1 1 1
 EOF
 $ECHO "  running the nscf calculation for Si...\c"
 $PW_COMMAND < si.nscf.in > si.nscf.out
+check_failure $?
 $ECHO " done"
 
 # calculation of the dynamical matrix at the X-point
@@ -188,7 +201,7 @@ phonons of Si at the X-point
  &inputph
   tr2_ph=1.0d-12,
   prefix='si',
-  trans=.true., 
+  trans=.true.,
   amass(1)=28.0855,
   amass(2)=28.0855,
   outdir='$TMP_DIR/',
@@ -199,13 +212,14 @@ phonons of Si at the X-point
 EOF
 $ECHO "  running the phonon calculation for Si at X...\c"
 $PH_COMMAND < si.phX.in > si.phX.out
+check_failure $?
 $ECHO " done"
 
 # calculation of the anharmonic tensor at X
 cat > si.d3X.in << EOF
 Anharm at the X-point
 &inputph
-   prefix = 'si', 
+   prefix = 'si',
    fildrho = 'si.drho_X',
    fild0rho = 'si.drho_G',
    amass(1) = 28.0855,
@@ -216,6 +230,7 @@ Anharm at the X-point
 EOF
 $ECHO "  running the calculation of D3(0,X,-X)...\c"
 $D3_COMMAND < si.d3X.in > si.d3X.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example16/run_example b/examples/example16/run_example
--- a/examples/example16/run_example
+++ b/examples/example16/run_example
@@ -7,6 +7,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -50,7 +53,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -71,7 +74,7 @@ $ECHO "  running pw.x as:      $PW_COMMAND"
 $ECHO "  running pp.x as:      $PP_COMMAND"
 $ECHO "  running plotrho.x as: $PLOTRHO_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -95,7 +98,7 @@ cat > AlAs110re.scf.in << EOF
  /
  &electrons
     mixing_mode = 'plain'
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
     conv_thr =  1.0d-6
  /
  ATOMIC_SPECIES
@@ -121,6 +124,7 @@ K_POINTS {automatic}
 EOF
 $ECHO "  running the scf calculation...\c"
 $PW_COMMAND < AlAs110re.scf.in > AlAs110re.scf.out
+check_failure $?
 $ECHO " done"
 
 cat > AlAs110re.nonscf.in << EOF
@@ -136,12 +140,12 @@ cat > AlAs110re.nonscf.in << EOF
     ibrav=  8, celldm(1) =7.424621202, celldm(2)=1.414213576,
     celldm(3)= 6.00000,
     nat= 14, ntyp= 2,
-    occupations='smearing', smearing='gaussian', degauss=0.01, nbnd=34, 
+    occupations='smearing', smearing='gaussian', degauss=0.01, nbnd=34,
     ecutwfc =14.0,
  /
  &electrons
     mixing_mode = 'plain'
-    mixing_beta = 0.7 
+    mixing_beta = 0.7
     conv_thr =  1.0d-6
  /
  ATOMIC_SPECIES
@@ -167,6 +171,7 @@ K_POINTS {automatic}
 EOF
 $ECHO "  running the non-scf calculation...\c"
 $PW_COMMAND < AlAs110re.nonscf.in > AlAs110re.nonscf.out
+check_failure $?
 $ECHO " done"
 
 # post-processing for stm images (sample bias given in Ry!)
@@ -185,27 +190,29 @@ cat > AlAs110.pp_stm-.in << EOF
    weight(1)=1.0
    iflag=2
    output_format=2
-   e1(1)=7.0, e1(2)=0.0,     e1(3)=0.0      
+   e1(1)=7.0, e1(2)=0.0,     e1(3)=0.0
    e2(1)=0.0, e2(2)=7.07107, e2(3)=0.0
    x0(1)=0.0, x0(2)=-0.18,   x0(3)=3.25
-   nx=36 ,ny=56     
+   nx=36 ,ny=56
    fileout='AlAs110-1.0'
  /
 EOF
 $ECHO
 $ECHO "  running the post-processing phase, negative bias...\c"
 $PP_COMMAND < AlAs110.pp_stm-.in > AlAs110.pp_stm-.out
+check_failure $?
 $ECHO " done"
 
 # run plotrho to do the figure
 cat > AlAs110.plotrho-.in << EOF
 AlAs110-1.0
 AlAs110-1.0eV.ps
-n  
-0.00005 0.0078  8 
+n
+0.00005 0.0078  8
 EOF
 $ECHO "  running plotrho on negative bias data...\c"
 $PLOTRHO_COMMAND < AlAs110.plotrho-.in > AlAs110.plotrho-.out
+check_failure $?
 $ECHO " done"
 
 # post-processing for stm images (as before, but positive bias)
@@ -224,27 +231,29 @@ cat > AlAs110.pp_stm+.in << EOF
    weight(1)=1.0
    iflag=2
    output_format=2
-   e1(1)=7.0, e1(2)=0.0,     e1(3)=0.0      
+   e1(1)=7.0, e1(2)=0.0,     e1(3)=0.0
    e2(1)=0.0, e2(2)=7.07107, e2(3)=0.0
    x0(1)=0.0, x0(2)=-0.18,   x0(3)=3.25
-   nx=36 ,ny=56     
+   nx=36 ,ny=56
    fileout='AlAs110+1.0'
  /
 EOF
 $ECHO "  running the post-processing phase, positive bias...\c"
 $PP_COMMAND < AlAs110.pp_stm+.in > AlAs110.pp_stm+.out
+check_failure $?
 $ECHO " done"
 
 # plotrho
 cat > AlAs110.plotrho+.in << EOF
 AlAs110+1.0
 AlAs110+1.0eV.ps
-n  
-0.00002 0.0021  8 
+n
+0.00002 0.0021  8
 EOF
 $ECHO "  running plotrho on positive bias data...\c"
 $PLOTRHO_COMMAND < AlAs110.plotrho+.in > AlAs110.plotrho+.out
+check_failure $?
 $ECHO " done"
 
-$ECHO 
+$ECHO
 $ECHO " $EXAMPLE_DIR: done"
diff --git a/examples/example21/run_example b/examples/example21/run_example
--- a/examples/example21/run_example
+++ b/examples/example21/run_example
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
@@ -7,13 +13,16 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
 $ECHO "This example shows how to use cp.x to perform molecular dynamics"
 $ECHO "simulation of medium to large systems."
 
-# set the needed environment variables 
+# set the needed environment variables
 . ../environment_variables
 
 # required executables and pseudopotentials
@@ -28,7 +37,7 @@ $ECHO "  checking that needed directories and files exist...\c"
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
-    if test ! -d $DIR ; then 
+    if test ! -d $DIR ; then
         $ECHO
         $ECHO "ERROR: $DIR not existent or not a directory"
         $ECHO "Aborting"
@@ -83,7 +92,7 @@ cat > h2o-32.in << EOF
     ndr = 50,
     ndw = -1,
     nstep  = 10,
-    iprint = 10, 
+    iprint = 10,
     isave  = 100,
     tstress = .TRUE.,
     tprnfor = .TRUE.,
@@ -94,13 +103,13 @@ cat > h2o-32.in << EOF
     outdir='$TMP_DIR/',
  /
  &system
-    ibrav = 14, 
-    celldm(1) = 18.65, 
-    celldm(2) = 1.0, 
-    celldm(3) = 1.0, 
-    celldm(4) = 0.0, 
-    celldm(5) = 0.0, 
-    celldm(6) = 0.0, 
+    ibrav = 14,
+    celldm(1) = 18.65,
+    celldm(2) = 1.0,
+    celldm(3) = 1.0,
+    celldm(4) = 0.0,
+    celldm(5) = 0.0,
+    celldm(6) = 0.0,
     nat = 96,
     ntyp = 2,
     nbnd = 128,
@@ -241,6 +250,7 @@ EOF
 $ECHO "  running the calculation with 32 H2O molecules...\c"
 if test "0$1" -ge 32 ; then
     $FPMD_COMMAND < h2o-32.in > h2o-32.out
+    check_failure $?
     $ECHO " done"
 else
     $ECHO " skipped" # too big, don't run
@@ -255,7 +265,7 @@ cat > h2o-64.in << EOF
     ndr = 50,
     ndw = -1,
     nstep  = 10,
-    iprint = 10, 
+    iprint = 10,
     isave  = 100,
     tstress = .TRUE.,
     tprnfor = .TRUE.,
@@ -266,13 +276,13 @@ cat > h2o-64.in << EOF
     outdir='$TMP_DIR/',
  /
  &system
-    ibrav = 14, 
-    celldm(1) = 18.65, 
-    celldm(2) = 1.0, 
-    celldm(3) = 2.0, 
-    celldm(4) = 0.0, 
-    celldm(5) = 0.0, 
-    celldm(6) = 0.0, 
+    ibrav = 14,
+    celldm(1) = 18.65,
+    celldm(2) = 1.0,
+    celldm(3) = 2.0,
+    celldm(4) = 0.0,
+    celldm(5) = 0.0,
+    celldm(6) = 0.0,
     nat = 192,
     ntyp = 2,
     nbnd = 256,
@@ -506,6 +516,7 @@ EOF
 $ECHO "  running the calculation with 64 H2O molecules...\c"
 if test "0$1" -ge 64 ; then
     $FPMD_COMMAND < h2o-64.in > h2o-64.out
+    check_failure $?
     $ECHO " done"
 else
     $ECHO " skipped" # too big, don't run
@@ -520,7 +531,7 @@ cat > h2o-128.in << EOF
     ndr = 50,
     ndw = -1,
     nstep  = 10,
-    iprint = 10, 
+    iprint = 10,
     isave  = 100,
     tstress = .TRUE.,
     tprnfor = .TRUE.,
@@ -531,13 +542,13 @@ cat > h2o-128.in << EOF
     outdir='$TMP_DIR/',
  /
  &system
-    ibrav = 14, 
-    celldm(1) = 18.65, 
-    celldm(2) = 2.0, 
-    celldm(3) = 2.0, 
-    celldm(4) = 0.0, 
-    celldm(5) = 0.0, 
-    celldm(6) = 0.0, 
+    ibrav = 14,
+    celldm(1) = 18.65,
+    celldm(2) = 2.0,
+    celldm(3) = 2.0,
+    celldm(4) = 0.0,
+    celldm(5) = 0.0,
+    celldm(6) = 0.0,
     nat = 384,
     ntyp = 2,
     nbnd = 512,
@@ -963,6 +974,7 @@ EOF
 $ECHO "  running the calculation with 128 H2O molecules...\c"
 if test "0$1" -ge 128 ; then
     $FPMD_COMMAND < h2o-128.in > h2o-128.out
+    check_failure $?
     $ECHO " done"
 else
     $ECHO " skipped" # too big, don't run
@@ -977,7 +989,7 @@ cat > h2o-256.in << EOF
     ndr = 50,
     ndw = -1,
     nstep  = 10,
-    iprint = 10, 
+    iprint = 10,
     isave  = 100,
     tstress = .TRUE.,
     tprnfor = .TRUE.,
@@ -988,13 +1000,13 @@ cat > h2o-256.in << EOF
     outdir='$TMP_DIR/',
  /
  &system
-    ibrav = 14, 
-    celldm(1) = 37.30, 
-    celldm(2) = 1.0, 
-    celldm(3) = 1.0, 
-    celldm(4) = 0.0, 
-    celldm(5) = 0.0, 
-    celldm(6) = 0.0, 
+    ibrav = 14,
+    celldm(1) = 37.30,
+    celldm(2) = 1.0,
+    celldm(3) = 1.0,
+    celldm(4) = 0.0,
+    celldm(5) = 0.0,
+    celldm(6) = 0.0,
     nat = 768,
     ntyp = 2,
     nbnd = 1024,
@@ -1804,6 +1816,7 @@ EOF
 $ECHO "  running the calculation with 256 H2O molecules...\c"
 if test "0$1" -ge 256 ; then
     $FPMD_COMMAND < h2o-256.in > h2o-256.out
+    check_failure $?
     $ECHO " done"
 else
     $ECHO " skipped" # too big, don't run
@@ -1818,7 +1831,7 @@ cat > h2o-384.in << EOF
     ndr = 50,
     ndw = -1,
     nstep  = 10,
-    iprint = 10, 
+    iprint = 10,
     isave  = 100,
     tstress = .TRUE.,
     tprnfor = .TRUE.,
@@ -1829,13 +1842,13 @@ cat > h2o-384.in << EOF
     outdir='$TMP_DIR/',
  /
  &system
-    ibrav = 14, 
-    celldm(1) = 37.30, 
-    celldm(2) = 1.0, 
-    celldm(3) = 1.5, 
-    celldm(4) = 0.0, 
-    celldm(5) = 0.0, 
-    celldm(6) = 0.0, 
+    ibrav = 14,
+    celldm(1) = 37.30,
+    celldm(2) = 1.0,
+    celldm(3) = 1.5,
+    celldm(4) = 0.0,
+    celldm(5) = 0.0,
+    celldm(6) = 0.0,
     nat = 1152,
     ntyp = 2,
     nbnd = 1536,
@@ -3029,6 +3042,7 @@ EOF
 $ECHO "  running the calculation with 384 H2O molecules...\c"
 if test "0$1" -ge 384 ; then
     $FPMD_COMMAND < h2o-384.in > h2o-384.out
+    check_failure $?
     $ECHO " done"
 else
     $ECHO " skipped" # too big, don't run
@@ -3043,7 +3057,7 @@ cat > h2o-512.in << EOF
     ndr = 50,
     ndw = -1,
     nstep  = 10,
-    iprint = 10, 
+    iprint = 10,
     isave  = 100,
     tstress = .TRUE.,
     tprnfor = .TRUE.,
@@ -3054,13 +3068,13 @@ cat > h2o-512.in << EOF
     outdir='$TMP_DIR/',
  /
  &system
-    ibrav = 14, 
-    celldm(1) = 37.30, 
-    celldm(2) = 1.0, 
-    celldm(3) = 2.0, 
-    celldm(4) = 0.0, 
-    celldm(5) = 0.0, 
-    celldm(6) = 0.0, 
+    ibrav = 14,
+    celldm(1) = 37.30,
+    celldm(2) = 1.0,
+    celldm(3) = 2.0,
+    celldm(4) = 0.0,
+    celldm(5) = 0.0,
+    celldm(6) = 0.0,
     nat = 1536,
     ntyp = 2,
     nbnd = 2048,
@@ -4638,6 +4652,7 @@ EOF
 $ECHO "  running the calculation with 512 H2O molecules...\c"
 if test "0$1" -ge 512 ; then
     $FPMD_COMMAND < h2o-512.in > h2o-512.out
+    check_failure $?
     $ECHO " done"
 else
     $ECHO " skipped" # too big, don't run
diff --git a/examples/example22/run_example b/examples/example22/run_example
--- a/examples/example22/run_example
+++ b/examples/example22/run_example
@@ -1,12 +1,15 @@
 #!/bin/sh
-                                                                                
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -57,7 +60,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -80,7 +83,7 @@ $ECHO "  running ph.x as: $PH_COMMAND"
 $ECHO "  running bands.x as: $BANDS_COMMAND"
 $ECHO "  running pwcond.x as: $PWCOND_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -99,7 +102,7 @@ Pt
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =7.42, nat=  1, ntyp= 1,
     lspinorb=.true.,
     noncolin=.true.,
@@ -107,22 +110,23 @@ Pt
     occupations='smearing',
     degauss=0.02,
     smearing='mp',
-    ecutwfc =30.0, 
-    ecutrho =250.0, 
+    ecutwfc =30.0,
+    ecutrho =250.0,
  /
  &electrons
-    mixing_beta = 0.7, 
+    mixing_beta = 0.7,
     conv_thr =  1.0d-8
  /
 ATOMIC_SPECIES
 Pt  79.90    Ptrel.RRKJ3.UPF
 ATOMIC_POSITIONS
-Pt  0.0000000   0.00000000   0.0  
+Pt  0.0000000   0.00000000   0.0
 K_POINTS AUTOMATIC
-4 4 4 1 1 1 
+4 4 4 1 1 1
 EOF
 $ECHO "  running the scf calculation for Pt with spin-orbit coupling...\c"
 $PW_COMMAND < pt.scf.in > pt.scf.out
+check_failure $?
 $ECHO " done"
 
 # a non self-consistent calculation
@@ -137,7 +141,7 @@ Pt
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =7.42, nat=  1, ntyp= 1,
     lspinorb=.true.,
     noncolin=.true.,
@@ -145,18 +149,18 @@ Pt
     occupations='smearing',
     degauss=0.02,
     smearing='mp',
-    ecutwfc =30.0, 
-    ecutrho =250.0, 
+    ecutwfc =30.0,
+    ecutrho =250.0,
  /
  &electrons
-    mixing_beta = 0.7, 
+    mixing_beta = 0.7,
     conv_thr =  1.0d-8
  /
 ATOMIC_SPECIES
 Pt  79.90    Ptrel.RRKJ3.UPF
 ATOMIC_POSITIONS
-Pt  0.0000000   0.00000000   0.0  
-K_POINTS 
+Pt  0.0000000   0.00000000   0.0
+K_POINTS
 8
 0.0 0.0 0.0 1.0
 0.1 0.0 0.0 1.0
@@ -169,6 +173,7 @@ K_POINTS
 EOF
 $ECHO "  running the non-scf calculation for Pt with spin-orbit coupling...\c"
 $PW_COMMAND < pt.nscf.in > pt.nscf.out
+check_failure $?
 $ECHO " done"
 
 cat > pt.bands.in << EOF
@@ -197,7 +202,7 @@ Pt
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =7.42, nat=  1, ntyp= 1,
     lspinorb=.true.,
     noncolin=.true.,
@@ -205,25 +210,24 @@ Pt
     occupations='smearing',
     degauss=0.02,
     smearing='mp',
-    ecutwfc =30.0, 
-    ecutrho =250.0, 
+    ecutwfc =30.0,
+    ecutrho =250.0,
  /
  &electrons
-    mixing_beta = 0.7, 
+    mixing_beta = 0.7,
     conv_thr =  1.0d-8
  /
 ATOMIC_SPECIES
 Pt  79.90    Ptrel.RRKJ3.UPF
 ATOMIC_POSITIONS
-Pt  0.0000000   0.00000000   0.0  
+Pt  0.0000000   0.00000000   0.0
 K_POINTS AUTOMATIC
-2 2 2 1 1 1 
+2 2 2 1 1 1
 EOF
 $ECHO "  running the scf calculation for Pt with spin-orbit coupling...\c"
 $PW_COMMAND < pt.scf_ph.in > pt.scf_ph.out
+check_failure $?
 $ECHO " done"
-
-
 
 cat > pt.ph.in << EOF
 phonons of Pt at Gamma
@@ -240,6 +244,7 @@ phonons of Pt at Gamma
 EOF
 $ECHO "  running the phonon calculation for Pt with spin-orbit coupling...\c"
 $PH_COMMAND < pt.ph.in > pt.ph.out
+check_failure $?
 $ECHO " done"
 
 cat > pt.nscf_ph.in << EOF
@@ -252,7 +257,7 @@ Pt
     pseudo_dir = '$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
  /
- &system    
+ &system
     ibrav=  2, celldm(1) =7.42, nat=  1, ntyp= 1,
     lspinorb=.true.,
     noncolin=.true.,
@@ -260,11 +265,11 @@ Pt
     occupations='smearing',
     degauss=0.02,
     smearing='mp',
-    ecutwfc =30.0, 
-    ecutrho =250.0, 
+    ecutwfc =30.0,
+    ecutrho =250.0,
  /
  &electrons
-    mixing_beta = 0.7, 
+    mixing_beta = 0.7,
     conv_thr =  1.0d-8
  /
  &phonon
@@ -275,12 +280,13 @@ Pt
 ATOMIC_SPECIES
 Pt  79.90    Ptrel.RRKJ3.UPF
 ATOMIC_POSITIONS
-Pt  0.0000000   0.00000000   0.0  
+Pt  0.0000000   0.00000000   0.0
 K_POINTS AUTOMATIC
-2 2 2 1 1 1 
+2 2 2 1 1 1
 EOF
 $ECHO "  running the nscf calculation for Pt with spin-orbit coupling...\c"
 $PW_COMMAND < pt.nscf_ph.in > pt.nscf_ph.out
+check_failure $?
 $ECHO " done"
 
 cat > pt.phX.in << EOF
@@ -298,8 +304,8 @@ phonons of Pt at X
 EOF
 $ECHO "  running the phonon calculation at X for Pt with spin-orbit coupling...\c"
 $PH_COMMAND < pt.phX.in > pt.phX.out
+check_failure $?
 $ECHO " done"
-
 
 # a self-consistent calculation of Pt in a tetragonal cell
 cat > pt.tet.in << EOF
@@ -312,18 +318,18 @@ cat > pt.tet.in << EOF
     prefix='ptt',
  /
  &system
-    ibrav = 6, 
-    celldm(1) =5.23, 
-    celldm(3) =1.4142, 
-    nat= 2, 
+    ibrav = 6,
+    celldm(1) =5.23,
+    celldm(3) =1.4142,
+    nat= 2,
     ntyp= 1,
     noncolin=.true.,
     lspinorb=.true.,
     starting_magnetization(1)=0.0,
-    ecutwfc = 30.0, 
+    ecutwfc = 30.0,
     ecutrho = 250.0,
-    occupations='smearing', 
-    smearing='methfessel-paxton', 
+    occupations='smearing',
+    smearing='methfessel-paxton',
     degauss=0.02
  /
  &electrons
@@ -331,24 +337,25 @@ cat > pt.tet.in << EOF
     mixing_beta = 0.7
  /
 ATOMIC_SPECIES
- Pt 58.69 Ptrel.RRKJ3.UPF 
+ Pt 58.69 Ptrel.RRKJ3.UPF
 ATOMIC_POSITIONS
- Pt 0.  0.  0. 
+ Pt 0.  0.  0.
  Pt 0.5 0.5 0.7071
 K_POINTS (automatic)
- 4 4 3 1 1 1                
+ 4 4 3 1 1 1
 EOF
 $ECHO "  running the scf calculation for Pt with tetragonal cell...\c"
 $PW_COMMAND < pt.tet.in > pt.tet.out
+check_failure $?
 $ECHO " done"
 
-# Calculation of the complex bands of Pt 
+# Calculation of the complex bands of Pt
 cat > pt.cond.in << EOF
  &inputcond
-    outdir='$TMP_DIR/'     
+    outdir='$TMP_DIR/'
     prefixl='ptt'
     band_file = 'bands.pt'
-    ikind=0  
+    ikind=0
     energy0=0.0d0
     denergy=-0.2d0
     ewind=4.d0
@@ -360,6 +367,7 @@ cat > pt.cond.in << EOF
 EOF
 $ECHO "  running the calculation of the complex bands of Pt...\c"
 $PWCOND_COMMAND < pt.cond.in > pt.cond.out
+check_failure $?
 $ECHO " done"
 
 cat > pt4.in << EOF
@@ -371,17 +379,17 @@ cat > pt4.in << EOF
     prefix='pt4',
  /
  &system
-    ibrav = 6, 
-    celldm(1) =5.23, 
-    celldm(3) =2.8284, 
-    nat= 4, 
+    ibrav = 6,
+    celldm(1) =5.23,
+    celldm(3) =2.8284,
+    nat= 4,
     ntyp= 1,
     noncolin=.true.,
     lspinorb=.true.,
-    ecutwfc = 25.0, 
+    ecutwfc = 25.0,
     ecutrho = 150.0,
-    occupations='smearing', 
-    smearing='methfessel-paxton', 
+    occupations='smearing',
+    smearing='methfessel-paxton',
     degauss=0.02
  /
  &electrons
@@ -389,26 +397,27 @@ cat > pt4.in << EOF
     mixing_beta = 0.7
  /
 ATOMIC_SPECIES
- Pt 58.69 Ptrel.RRKJ3.UPF 
+ Pt 58.69 Ptrel.RRKJ3.UPF
 ATOMIC_POSITIONS
- Pt 0.  0.  0. 
+ Pt 0.  0.  0.
  Pt 0.5 0.5 0.7071
- Pt 0.  0.  1.4142 
+ Pt 0.  0.  1.4142
  Pt 0.5 0.5 2.1213
 K_POINTS (automatic)
- 2 2 1 1 1 1                
+ 2 2 1 1 1 1
 EOF
 $ECHO "  running the self-consistent calculation of fcc-Pt with 4 atoms...\c"
 $PW_COMMAND < pt4.in > pt4.out
+check_failure $?
 $ECHO " done"
 
-# Calculation of the transmission of Pt 
+# Calculation of the transmission of Pt
 cat > pt.cond_t.in << EOF
  &inputcond
-    outdir='$TMP_DIR/'     
+    outdir='$TMP_DIR/'
     prefixt='pt4'
     bdl=1.4142,
-    ikind=1  
+    ikind=1
     energy0=0.0d0
     denergy=-0.2d0
     ewind=4.d0
@@ -420,6 +429,7 @@ cat > pt.cond_t.in << EOF
 EOF
 $ECHO "  running the calculation of the transmission of fcc Pt...\c"
 $PWCOND_COMMAND < pt.cond_t.in > pt.cond_t.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example23/run_example b/examples/example23/run_example
--- a/examples/example23/run_example
+++ b/examples/example23/run_example
@@ -1,12 +1,15 @@
 #!/bin/sh
-                                                                                
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -52,7 +55,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -69,7 +72,7 @@ CP_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
 $ECHO
 $ECHO "  running cp.x as: $CP_COMMAND"
 $ECHO
- 
+
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
 rm -rf $TMP_DIR/*
@@ -80,7 +83,7 @@ cat > h2o.wannier.in << EOF
   calculation   = "cp-wf",
   restart_mode  = "from_scratch",
   nstep         = 100,
-  iprint        = 100, 
+  iprint        = 100,
   isave         = 100,
   dt            = 4.D0,
   etot_conv_thr = 1.D-16,
@@ -90,8 +93,8 @@ cat > h2o.wannier.in << EOF
   outdir        = "$TMP_DIR/",
 /
 &SYSTEM
-  ibrav     = 1, 
-  celldm(1) = 20.0, 
+  ibrav     = 1,
+  celldm(1) = 20.0,
   nat       = 3,
   ntyp      = 2,
   ecutwfc   = 25.D0,
@@ -110,7 +113,7 @@ cat > h2o.wannier.in << EOF
 /
 &WANNIER
   adapt  = .true.,
-  nsteps = 10, 
+  nsteps = 10,
 /
 ATOMIC_SPECIES
 O  16.D0  O_US.van
@@ -122,6 +125,7 @@ H      9.6757    11.7325    10.000
 EOF
 $ECHO "  running the Wannier functions calculation...\c"
 $CP_COMMAND < h2o.wannier.in > h2o.wannier.out
+check_failure $?
 $ECHO "  Wannier functions spreads...\c">> h2o.wannier.out
 $ECHO "">> h2o.wannier.out
   tail -4 $TMP_DIR/h2o_mol.spr  >> h2o.wannier.out
@@ -137,7 +141,7 @@ cat > h2o.efield.in << EOF
   restart_mode  = "reset_counters",
   ndw           = 51
   nstep         = 200,
-  iprint        = 100, 
+  iprint        = 100,
   isave         = 100,
   dt            = 6.D0,
   prefix        = "h2o_mol",
@@ -145,8 +149,8 @@ cat > h2o.efield.in << EOF
   outdir        = "$TMP_DIR/",
 /
 &SYSTEM
-  ibrav     = 1, 
-  celldm(1) = 20.0, 
+  ibrav     = 1,
+  celldm(1) = 20.0,
   nat       = 3,
   ntyp      = 2,
   ecutwfc   = 25.D0,
@@ -178,6 +182,7 @@ H      9.6757    11.7325    10.000
 EOF
 $ECHO "  running the calculation with electric field...\c"
 $CP_COMMAND < h2o.efield.in > h2o.efield.out
+check_failure $?
 
 $ECHO
 $ECHO "$EXAMPLE_DIR: done"
diff --git a/examples/example25/run_example b/examples/example25/run_example
--- a/examples/example25/run_example
+++ b/examples/example25/run_example
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
@@ -7,13 +13,16 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
 $ECHO "This example shows how to use pw.x to calculate the total energy of FeO"
 $ECHO "using LDA+U approximation. Read file README for more details"
 
-# set the needed environment variables 
+# set the needed environment variables
 . ../environment_variables
 
 # required executables and pseudopotentials
@@ -28,7 +37,7 @@ $ECHO "  checking that needed directories and files exist...\c"
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
-    if test ! -d $DIR ; then 
+    if test ! -d $DIR ; then
         $ECHO
         $ECHO "ERROR: $DIR not existent or not a directory"
         $ECHO "Aborting"
@@ -77,8 +86,8 @@ $ECHO " done"
 
 # self-consistent calculation with standard LDA
 cat > feo_LDA.in << EOF
-FeO 
-FeO Wustite in LDA 
+FeO
+FeO Wustite in LDA
  &control
     calculation = 'scf'
     restart_mode='from_scratch',
@@ -90,7 +99,7 @@ FeO Wustite in LDA
     ibrav=  0, celldm(1)=8.19, nat=  4, ntyp= 3,
     ecutwfc = 30.0, ecutrho = 240.0, nbnd=20,
     starting_magnetization(1)= 0.0,
-    starting_magnetization(2)= 0.5, 
+    starting_magnetization(2)= 0.5,
     starting_magnetization(3)=-0.5,
     occupations='smearing', smearing='gauss', degauss=0.01,
     nspin=2,
@@ -98,7 +107,7 @@ FeO Wustite in LDA
  /
  &electrons
     mixing_mode = 'plain'
-    mixing_beta = 0.3 
+    mixing_beta = 0.3
     conv_thr =  1.0d-6
     mixing_fixed_ns = 0
  /
@@ -113,13 +122,14 @@ ATOMIC_SPECIES
 ATOMIC_POSITIONS {crystal}
  O1  0.25 0.25 0.25
  O1  0.75 0.75 0.75
- Fe1 0.0  0.0  0.0 
+ Fe1 0.0  0.0  0.0
  Fe2 0.5  0.5  0.5
 K_POINTS {automatic}
 2 2 2 0 0 0
 EOF
 $ECHO "  running scf for FeO in LDA ...\c"
 $PW_COMMAND < feo_LDA.in > feo_LDA.out
+check_failure $?
 $ECHO " done"
 
 
@@ -130,7 +140,7 @@ $ECHO " done"
 
 # self-consistent calculation with standard ns initial value
 cat > feo_standard.in << EOF
-FeO 
+FeO
 FeO Wustite whithin LDA+U using standard initial ns matrices
  &control
     calculation = 'scf'
@@ -143,7 +153,7 @@ FeO Wustite whithin LDA+U using standard initial ns matrices
     ibrav=  0, celldm(1)=8.19, nat=  4, ntyp= 3,
     ecutwfc = 30.0, ecutrho = 240.0, nbnd=20,
     starting_magnetization(1)= 0.0,
-    starting_magnetization(2)= 0.5, 
+    starting_magnetization(2)= 0.5,
     starting_magnetization(3)=-0.5,
     occupations='smearing', smearing='gauss', degauss=0.01,
     nspin=2,
@@ -151,7 +161,7 @@ FeO Wustite whithin LDA+U using standard initial ns matrices
  /
  &electrons
     mixing_mode = 'plain'
-    mixing_beta = 0.3 
+    mixing_beta = 0.3
     conv_thr =  1.0d-6
     mixing_fixed_ns = 0
  /
@@ -166,13 +176,14 @@ ATOMIC_SPECIES
 ATOMIC_POSITIONS {crystal}
  O1  0.25 0.25 0.25
  O1  0.75 0.75 0.75
- Fe1 0.0  0.0  0.0 
+ Fe1 0.0  0.0  0.0
  Fe2 0.5  0.5  0.5
 K_POINTS {automatic}
 2 2 2 0 0 0
 EOF
 $ECHO "  running scf for FeO in LDA+U using standard ns initial matrices...\c"
 $PW_COMMAND < feo_standard.in > feo_standard.out
+check_failure $?
 $ECHO " done"
 
 # clean TMP_DIR
@@ -195,7 +206,7 @@ FeO Wustite whithin LDA+U with user-defined ns initial matrices
     ibrav=  0, celldm(1)=8.19, nat=  4, ntyp= 3,
     ecutwfc = 30.0, ecutrho = 240.0, nbnd=20,
     starting_magnetization(1)= 0.0,
-    starting_magnetization(2)= 0.5, 
+    starting_magnetization(2)= 0.5,
     starting_magnetization(3)=-0.5,
     occupations='smearing', smearing='gauss', degauss=0.01,
     nspin=2,
@@ -205,7 +216,7 @@ FeO Wustite whithin LDA+U with user-defined ns initial matrices
  /
  &electrons
     mixing_mode = 'plain'
-    mixing_beta = 0.3 
+    mixing_beta = 0.3
     conv_thr =  1.0d-6
     mixing_fixed_ns = 0
  /
@@ -220,17 +231,18 @@ ATOMIC_SPECIES
 ATOMIC_POSITIONS {crystal}
  O1  0.25 0.25 0.25
  O1  0.75 0.75 0.75
- Fe1 0.0  0.0  0.0 
+ Fe1 0.0  0.0  0.0
  Fe2 0.5  0.5  0.5
 K_POINTS {automatic}
 2 2 2 0 0 0
 EOF
 $ECHO "  running scf for FeO in LDA+U using user-defined ns initial matrices...\c"
 $PW_COMMAND < feo_user_ns.in > feo_user_ns.out
+check_failure $?
 $ECHO " done"
 
 # again self-consistent calculation with standard LDA
-$ECHO 
+$ECHO
 $ECHO "  use LDA+U projecting on wannier function: "
 $ECHO "  1) running again scf for FeO using LDA ...\c"
 $PW_COMMAND < feo_LDA.in > feo_LDA_again.out
@@ -238,13 +250,15 @@ $ECHO " done"
 $ECHO "  2) running poormanwannier post-processing to build Wannier projectors ...\c"
 cat > pmw.in << EOF
  &inputpp
-    outdir='$TMP_DIR/', 
+    outdir='$TMP_DIR/',
     prefix='feo_af',
-    first_band=9, last_band=20, 
+    first_band=9, last_band=20,
  /
 EOF
 $PMW_COMMAND < pmw.in > pmw.out
+check_failure $?
 $ECHO " done"
+
 # self-consistent calculation with user defined ns + Wannier
 cat > feo_wannier.in << EOF
 FeO
@@ -260,7 +274,7 @@ FeO Wustite whithin LDA+U with user defined ns + Wannier
     ibrav=  0, celldm(1)=8.19, nat=  4, ntyp= 3,
     ecutwfc = 30.0, ecutrho = 240.0, nbnd=20,
     starting_magnetization(1)= 0.0,
-    starting_magnetization(2)= 0.5, 
+    starting_magnetization(2)= 0.5,
     starting_magnetization(3)=-0.5,
     occupations='smearing', smearing='gauss', degauss=0.01,
     nspin=2,
@@ -271,7 +285,7 @@ FeO Wustite whithin LDA+U with user defined ns + Wannier
  /
  &electrons
     mixing_mode = 'plain'
-    mixing_beta = 0.3 
+    mixing_beta = 0.3
     conv_thr =  1.0d-6
     mixing_fixed_ns = 0
  /
@@ -286,13 +300,14 @@ ATOMIC_SPECIES
 ATOMIC_POSITIONS {crystal}
  O1  0.25 0.25 0.25
  O1  0.75 0.75 0.75
- Fe1 0.0  0.0  0.0 
+ Fe1 0.0  0.0  0.0
  Fe2 0.5  0.5  0.5
 K_POINTS {automatic}
 2 2 2 0 0 0
 EOF
 $ECHO "  3) running scf for FeO in LDA+U using Wannier projectors...\c"
 $PW_COMMAND < feo_wannier.in > feo_wannier.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example26/run_example b/examples/example26/run_example
--- a/examples/example26/run_example
+++ b/examples/example26/run_example
@@ -1,5 +1,11 @@
 #!/bin/sh
-#
+
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # 30 min
 # contributed by Y. Kanai (ykanai@princeton.edu)
 # reference: JCP 121, 3359 (2004)
@@ -11,6 +17,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -19,7 +28,7 @@ $ECHO "(MEP) using string method (smd)."
 $ECHO
 $ECHO " This script runs a sequence of CP-SMD calculations to get the MEP"
 $ECHO " 1. Minimize electronic degrees of freedom"
-$ECHO " 2. Locate the MEP" 
+$ECHO " 2. Locate the MEP"
 
 # set the needed environment variables
 . ../environment_variables
@@ -132,9 +141,9 @@ cat > smd1.in << EOF
     smd_maxlm = 100,
     smd_codf = 50,
     smd_forf = 50,
-    smd_smwf = 1, 
-    smd_ene_ini = -1.63640, 
-    smd_ene_fin = -1.63640  
+    smd_smwf = 1,
+    smd_ene_ini = -1.63640,
+    smd_ene_fin = -1.63640
  /
 ATOMIC_SPECIES
 H   1.0  H_US.van  1
@@ -152,6 +161,7 @@ $ECHO "  running first SMD calculation ...\c"
 if test "0$2" -ge 1 ; then
  if test "0$1" -le 1 ; then
     $CP_COMMAND < smd1.in > smd1.out
+    check_failure $?
     $ECHO " done"
  else
     $ECHO " skipped"
@@ -223,6 +233,7 @@ $ECHO "  running second SMD calculation ...\c"
 if test "0$2" -ge 2 ; then
  if test "0$1" -le 2 ; then
     $CP_COMMAND < smd2.in > smd2.out
+    check_failure $?
     $ECHO " done"
  else
     $ECHO " skipped"
@@ -294,6 +305,7 @@ $ECHO "  running third SMD calculation ...\c"
 if test "0$2" -ge 3 ; then
  if test "0$1" -le 3 ; then
     $CP_COMMAND < smd3.in > smd3.out
+    check_failure $?
     $ECHO " done"
  else
     $ECHO " skipped"
@@ -365,6 +377,7 @@ $ECHO "  running fourth SMD calculation ...\c"
 if test "0$2" -ge 4 ; then
  if test "0$1" -le 4 ; then
     $CP_COMMAND < smd4.in > smd4.out
+    check_failure $?
     $ECHO " done"
  else
     $ECHO " skipped"
@@ -436,6 +449,7 @@ $ECHO "  running fifth SMD calculation ...\c"
 if test "0$2" -ge 5 ; then
  if test "0$1" -le 5 ; then
     $CP_COMMAND < smd5.in > smd5.out
+    check_failure $?
     $ECHO " done"
  else
     $ECHO " skipped"
@@ -507,6 +521,7 @@ $ECHO "  running sixth SMD calculation ...\c"
 if test "0$2" -ge 6 ; then
  if test "0$1" -le 6 ; then
     $CP_COMMAND < smd6.in > smd6.out
+    check_failure $?
     $ECHO " done"
  else
     $ECHO " skipped"
@@ -578,6 +593,7 @@ $ECHO "  running seventh SMD calculation ...\c"
 if test "0$2" -ge 7 ; then
  if test "0$1" -le 7 ; then
     $CP_COMMAND < smd7.in > smd7.out
+    check_failure $?
     $ECHO " done"
  else
     $ECHO " skipped"
diff --git a/examples/example30/run_example b/examples/example30/run_example
--- a/examples/example30/run_example
+++ b/examples/example30/run_example
@@ -1,11 +1,20 @@
 #!/bin/sh
 
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
+
+# function to test the exit status of a job
+. ../check_failure.sh
 
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
@@ -16,7 +25,7 @@ $ECHO "modern theory of the polarization. The example shows how to"
 $ECHO "calculate high-frequency and static dielectric constants and"
 $ECHO "Born effective charges."
 
-# set the needed environment variables 
+# set the needed environment variables
 . ../environment_variables
 
 # required executables and pseudopotentials
@@ -31,7 +40,7 @@ $ECHO "  checking that needed directories and files exist...\c"
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
-    if test ! -d $DIR ; then 
+    if test ! -d $DIR ; then
         $ECHO
         $ECHO "ERROR: $DIR not existent or not a directory"
         $ECHO "Aborting"
@@ -92,7 +101,7 @@ cat > mgo.cp.cg.in << EOF
   pseudo_dir = '$PSEUDO_DIR/',
   outdir='$TMP_DIR/'
 /
-  
+
 &SYSTEM
   ibrav = 1,
   celldm(1) = 15.912,
@@ -110,7 +119,7 @@ cat > mgo.cp.cg.in << EOF
   nr1b= 30, nr2b = 30, nr3b = 30,
   nspin=1,
 /
-  
+
 &ELECTRONS
   emass = 1000.d0,
   emass_cutoff = 4.d0,
@@ -124,7 +133,7 @@ cat > mgo.cp.cg.in << EOF
   epol = 3
   efield = 0.0
 /
-  
+
 &IONS
   ion_dynamics = 'none',
   ion_damping = 0.,
@@ -133,83 +142,85 @@ cat > mgo.cp.cg.in << EOF
   ion_radius(1) = 0.8d0,
   ion_temperature = 'not_controlled',
 /
-  
+
 &CELL
   cell_dynamics = 'none',
 /
-  
+
 ATOMIC_SPECIES
  O  12.01 O.pz-rrkjus.UPF
  Mg 24.30 Mg.pz-n-vbc.UPF
 ATOMIC_POSITIONS (bohr)
-Mg   0.066300000   0.066300000   0.066300000  
-Mg  4.044300000   4.044300000   0.066300000   
-Mg   4.044300000   0.066300000   4.044300000 
+Mg   0.066300000   0.066300000   0.066300000
+Mg  4.044300000   4.044300000   0.066300000
+Mg   4.044300000   0.066300000   4.044300000
 Mg   0.066300000   4.044300000   4.044300000
-Mg   0.066300000   0.066300000   8.022300000  
+Mg   0.066300000   0.066300000   8.022300000
 Mg   4.044300000   4.044300000   8.022300000
-Mg   4.044300000   0.066300000  12.000300000  
-Mg   0.066300000   4.044300000  12.000300000 
-Mg   0.066300000   8.022300000   0.066300000  
-Mg   4.044300000  12.000300000   0.066300000 
-Mg   4.044300000   8.022300000   4.044300000  
-Mg   0.066300000  12.000300000   4.044300000 
-Mg   0.066300000   8.022300000   8.022300000  
-Mg   4.044300000  12.000300000   8.022300000  
-Mg   4.044300000   8.022300000  12.000300000 
-Mg   0.066300000  12.000300000  12.000300000  
-Mg   8.022300000   0.066300000   0.066300000 
-Mg  12.000300000   4.044300000   0.066300000  
+Mg   4.044300000   0.066300000  12.000300000
+Mg   0.066300000   4.044300000  12.000300000
+Mg   0.066300000   8.022300000   0.066300000
+Mg   4.044300000  12.000300000   0.066300000
+Mg   4.044300000   8.022300000   4.044300000
+Mg   0.066300000  12.000300000   4.044300000
+Mg   0.066300000   8.022300000   8.022300000
+Mg   4.044300000  12.000300000   8.022300000
+Mg   4.044300000   8.022300000  12.000300000
+Mg   0.066300000  12.000300000  12.000300000
+Mg   8.022300000   0.066300000   0.066300000
+Mg  12.000300000   4.044300000   0.066300000
 Mg  12.000300000   0.066300000   4.044300000
-Mg   8.022300000   4.044300000   4.044300000  
+Mg   8.022300000   4.044300000   4.044300000
 Mg   8.022300000   0.066300000   8.022300000
-Mg  12.000300000   4.044300000   8.022300000 
-Mg  12.000300000   0.066300000  12.000300000 
-Mg   8.022300000   4.044300000  12.000300000  
-Mg   8.022300000   8.022300000   0.066300000 
-Mg  12.000300000  12.000300000   0.066300000  
-Mg  12.000300000   8.022300000   4.044300000 
-Mg   8.022300000  12.000300000   4.044300000  
+Mg  12.000300000   4.044300000   8.022300000
+Mg  12.000300000   0.066300000  12.000300000
+Mg   8.022300000   4.044300000  12.000300000
+Mg   8.022300000   8.022300000   0.066300000
+Mg  12.000300000  12.000300000   0.066300000
+Mg  12.000300000   8.022300000   4.044300000
+Mg   8.022300000  12.000300000   4.044300000
 Mg   8.022300000   8.022300000   8.022300000
-Mg  12.000300000  12.000300000   8.022300000 
+Mg  12.000300000  12.000300000   8.022300000
 Mg  12.000300000   8.022300000  12.000300000
-Mg   8.022300000  12.000300000  12.000300000  
-O   0.066300000   0.066300000   4.044300000 
-O   4.044300000   4.044300000   4.044300000  
-O   4.044300000   0.066300000   8.022300000 
-O   0.066300000   4.044300000   8.022300000  
-O   0.066300000   0.066300000  12.000300000 
-O   4.044300000   4.044300000  12.000300000   
-O   4.044300000   0.066300000  15.978300000  
-O   0.066300000   4.044300000  15.978300000 
+Mg   8.022300000  12.000300000  12.000300000
+O   0.066300000   0.066300000   4.044300000
+O   4.044300000   4.044300000   4.044300000
+O   4.044300000   0.066300000   8.022300000
+O   0.066300000   4.044300000   8.022300000
+O   0.066300000   0.066300000  12.000300000
+O   4.044300000   4.044300000  12.000300000
+O   4.044300000   0.066300000  15.978300000
+O   0.066300000   4.044300000  15.978300000
 O   0.066300000   8.022300000   4.044300000
-O   4.044300000  12.000300000   4.044300000  
-O   4.044300000   8.022300000   8.022300000 
+O   4.044300000  12.000300000   4.044300000
+O   4.044300000   8.022300000   8.022300000
 O   0.066300000  12.000300000   8.022300000
-O   0.066300000   8.022300000  12.000300000 
-O   4.044300000  12.000300000  12.000300000  
-O   4.044300000   8.022300000  15.978300000 
-O   0.066300000  12.000300000  15.978300000 
-O   8.022300000   0.066300000   4.044300000 
+O   0.066300000   8.022300000  12.000300000
+O   4.044300000  12.000300000  12.000300000
+O   4.044300000   8.022300000  15.978300000
+O   0.066300000  12.000300000  15.978300000
+O   8.022300000   0.066300000   4.044300000
 O  12.000300000   4.044300000   4.044300000
 O  12.000300000   0.066300000   8.022300000
-O   8.022300000   4.044300000   8.022300000  
-O   8.022300000   0.066300000  12.000300000 
-O  12.000300000   4.044300000  12.000300000 
+O   8.022300000   4.044300000   8.022300000
+O   8.022300000   0.066300000  12.000300000
+O  12.000300000   4.044300000  12.000300000
 O  12.000300000   0.066300000  15.978300000
 O   8.022300000   4.044300000  15.978300000
 O   8.022300000   8.022300000   4.044300000
-O  12.000300000  12.000300000   4.044300000  
-O  12.000300000   8.022300000   8.022300000 
-O   8.022300000  12.000300000   8.022300000 
-O   8.022300000   8.022300000  12.000300000  
-O  12.000300000  12.000300000  12.000300000 
-O  12.000300000   8.022300000  15.978300000  
-O   8.022300000  12.000300000  15.978300000 
+O  12.000300000  12.000300000   4.044300000
+O  12.000300000   8.022300000   8.022300000
+O   8.022300000  12.000300000   8.022300000
+O   8.022300000   8.022300000  12.000300000
+O  12.000300000  12.000300000  12.000300000
+O  12.000300000   8.022300000  15.978300000
+O   8.022300000  12.000300000  15.978300000
 EOF
 $ECHO "  running the CG calculation for bulk MgO E_field=0. a.u. ...\c"
 $CP_COMMAND < mgo.cp.cg.in > mgo.cp.cg.out
+check_failure $?
 $ECHO " done"
+
 cat > mgo.cp.cg.efield.in << EOF
 &CONTROL
   calculation = 'cp',
@@ -224,7 +235,7 @@ cat > mgo.cp.cg.efield.in << EOF
   pseudo_dir = '$PSEUDO_DIR/',
   outdir='$TMP_DIR/'
 /
-   
+
 &SYSTEM
   ibrav = 1,
   celldm(1) = 15.912,
@@ -242,7 +253,7 @@ cat > mgo.cp.cg.efield.in << EOF
   nr1b= 30, nr2b = 30, nr3b = 30,
   nspin=1,
 /
-   
+
 &ELECTRONS
   emass = 1000.d0,
   emass_cutoff = 4.d0,
@@ -256,7 +267,7 @@ cat > mgo.cp.cg.efield.in << EOF
   epol = 3
   efield = 0.001
 /
-   
+
 &IONS
   ion_dynamics = 'none',
   ion_damping = 0.,
@@ -265,11 +276,11 @@ cat > mgo.cp.cg.efield.in << EOF
   ion_radius(1) = 0.8d0,
   ion_temperature = 'not_controlled',
 /
-   
+
 &CELL
   cell_dynamics = 'none',
 /
-   
+
 ATOMIC_SPECIES
  O  12.01 O.pz-rrkjus.UPF
  Mg 24.30 Mg.pz-n-vbc.UPF
@@ -341,8 +352,10 @@ O   8.022300000  12.000300000  15.978300000
 EOF
 $ECHO "  running the CG calculation for bulk MgO E_field=0.001 a.u. ...\c"
 $CP_COMMAND < mgo.cp.cg.efield.in > mgo.cp.cg.efield.out
+check_failure $?
 $ECHO " done"
-cat > mgo.cp.damp.efield.in << EOF 
+
+cat > mgo.cp.damp.efield.in << EOF
 &CONTROL
   calculation = 'cp',
   restart_mode = 'restart',
@@ -357,7 +370,7 @@ cat > mgo.cp.damp.efield.in << EOF
   pseudo_dir = '$PSEUDO_DIR/',
   outdir='$TMP_DIR/'
 /
-  
+
 &SYSTEM
   ibrav = 1,
   celldm(1) = 15.912,
@@ -375,7 +388,7 @@ cat > mgo.cp.damp.efield.in << EOF
   nr1b= 30, nr2b = 30, nr3b = 30,
   nspin=1,
 /
-  
+
 &ELECTRONS
   emass = 250.d0,
   emass_cutoff = 3.d0,
@@ -386,16 +399,16 @@ cat > mgo.cp.damp.efield.in << EOF
   epol = 3
   efield = 0.001
 /
-  
+
 &IONS
   ion_dynamics = 'verlet',
   ion_damping = 0.
 /
-  
+
 &CELL
   cell_dynamics = 'none',
 /
-  
+
 ATOMIC_SPECIES
  O  1.0 O.pz-rrkjus.UPF
  Mg 1.0 Mg.pz-n-vbc.UPF
@@ -467,6 +480,7 @@ O   8.022300000  12.000300000  15.978300000
 EOF
 $ECHO "  running the CP- damped MD calculation for bulk MgO E_field=0.001 a.u. ...\c"
 $CP_COMMAND < mgo.cp.damp.efield.in > mgo.cp.damp.efield.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example31/run_example b/examples/example31/run_example
--- a/examples/example31/run_example
+++ b/examples/example31/run_example
@@ -7,6 +7,9 @@ EXAMPLE_DIR=`pwd`
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
 
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -15,7 +18,7 @@ $ECHO "calculations in the presence of a finite homogeneous electric field "
 $ECHO "described through the modern theory of the polarization. The example"
 $ECHO "shows how to calculate high-frequency dielectric constant of bulk Silicon"
 
-# set the needed environment variables 
+# set the needed environment variables
 . ../environment_variables
 
 # required executables and pseudopotentials
@@ -30,7 +33,7 @@ $ECHO "  checking that needed directories and files exist...\c"
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
-    if test ! -d $DIR ; then 
+    if test ! -d $DIR ; then
         $ECHO
         $ECHO "ERROR: $DIR not existent or not a directory"
         $ECHO "Aborting"
@@ -65,13 +68,13 @@ for FILE in $PSEUDO_LIST ; do
 done
 $ECHO " done"
 
- 
+
 # how to run executables
 PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
 $ECHO
 $ECHO "  running pw.x as: $PW_COMMAND"
 $ECHO
- 
+
 
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
@@ -182,7 +185,9 @@ K_POINTS
 EOF
 $ECHO "  running the PW calculation for bulk Si no electric field ...\c"
 $PW_COMMAND < si.scf.in > si.scf.out
+check_failure $?
 $ECHO " done"
+
 cat > si.scf.efield.in << EOF
  &control
     calculation='scf'
@@ -286,8 +291,10 @@ K_POINTS
 EOF
 $ECHO "  running the PW calculation for bulk Si E_field=0.0  a.u. ...\c"
 $PW_COMMAND < si.scf.efield.in > si.scf.efield.out
+check_failure $?
 $ECHO " done"
-cat > si.scf.efield2.in << EOF 
+
+cat > si.scf.efield2.in << EOF
  &control
     calculation='scf'
     restart_mode='from_scratch',
@@ -298,7 +305,7 @@ cat > si.scf.efield2.in << EOF
     nberrycyc=3
     pseudo_dir='$PSEUDO_DIR/',
     outdir='$TMP_DIR/'
- 
+
  /
  &system
     ibrav= 1, celldm(1)=10.18, nat=  8, ntyp= 1,
@@ -391,6 +398,7 @@ K_POINTS
 EOF
 $ECHO "  running the PW calculation for bulk Si E_field=0.001  a.u. ...\c"
 $PW_COMMAND < si.scf.efield2.in > si.scf.efield2.out
+check_failure $?
 $ECHO " done"
 
 $ECHO
diff --git a/examples/example32/run_example b/examples/example32/run_example
--- a/examples/example32/run_example
+++ b/examples/example32/run_example
@@ -1,11 +1,20 @@
 #!/bin/sh
 
+###############################################################################
+##
+##  HIGH WERBOSITY EXAMPLE
+##
+###############################################################################
+
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
 
 # check whether echo has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
+
+# function to test the exit status of a job
+. ../check_failure.sh
 
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
@@ -16,7 +25,7 @@ $ECHO "molecule in vacuum. The coordinates of the atoms in the molecule are"
 $ECHO "already in a good ground state configuration, no geometry optimization"
 $ECHO "is required."
 
-# set the needed environment variables 
+# set the needed environment variables
 . ../environment_variables
 
 # required executables and pseudopotentials
@@ -31,7 +40,7 @@ $ECHO "  checking that needed directories and files exist...\c"
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
-    if test ! -d $DIR ; then 
+    if test ! -d $DIR ; then
         $ECHO
         $ECHO "ERROR: $DIR not existent or not a directory"
         $ECHO "Aborting"
@@ -66,13 +75,13 @@ for FILE in $PSEUDO_LIST ; do
 done
 $ECHO " done"
 
- 
+
 # how to run executables
 PW_COMMAND="$PARA_PREFIX $BIN_DIR/cpvib.x $PARA_POSTFIX"
 $ECHO
 $ECHO "  running cpvib.x as: $PW_COMMAND"
 $ECHO
- 
+
 
 # clean TMP_DIR
 $ECHO "  cleaning $TMP_DIR...\c"
@@ -140,6 +149,7 @@ EOF
 
 $ECHO "  running the CPVIB calculation for water molecule in vacuum ...\c"
 $PW_COMMAND < h2o.cp.in > h2o.cp.out
+check_failure $?
 $ECHO " done"
 
 $ECHO "  copying to local directory: h2o.vib.inp h2o.vib.analysis"
diff --git a/examples/example33/run_example b/examples/example33/run_example
--- a/examples/example33/run_example
+++ b/examples/example33/run_example
@@ -6,7 +6,10 @@ EXAMPLE_DIR=`pwd`
 
 # check whether ECHO has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
@@ -52,7 +55,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -118,9 +121,10 @@ EOF
 #
 $ECHO "  running the scf calculation...\c"
 $PW_COMMAND < ch4.scf.in > ch4.scf.out
+check_failure $?
 $ECHO " done"
 #
-# dynamic polarizability calculation 
+# dynamic polarizability calculation
 #
 cat > ch4.fpol.in << EOF
 
@@ -145,5 +149,8 @@ EOF
 #
 $ECHO "  running the dynamic polarizability calculation ...\c"
 $PH_COMMAND < ch4.fpol.in > ch4.fpol.out
+check_failure $?
 $ECHO " done"
 
+$ECHO
+$ECHO "$EXAMPLE_DIR : done"
diff --git a/examples/example34/run_example b/examples/example34/run_example
--- a/examples/example34/run_example
+++ b/examples/example34/run_example
@@ -6,14 +6,17 @@ EXAMPLE_DIR=`pwd`
 
 # check whether ECHO has the -e option
 if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi
-                                                                                
+
+# function to test the exit status of a job
+. ../check_failure.sh
+
 $ECHO
 $ECHO "$EXAMPLE_DIR : starting"
 $ECHO
 $ECHO "This example shows how to use vdw.x to calculate dynamic"
-$ECHO "polarizability of methane molecule in simplified version 
-       of the one in ph.x (see example33) by using Thomas-Fermi 
-       and von Weizsaecker approximation" 
+$ECHO "polarizability of methane molecule in simplified version
+       of the one in ph.x (see example33) by using Thomas-Fermi
+       and von Weizsaecker approximation"
 
 # set the needed environment variables
 . ../environment_variables
@@ -54,7 +57,7 @@ for FILE in $BIN_LIST ; do
         exit 1
     fi
 done
- 
+
 # check for pseudopotentials
 for FILE in $PSEUDO_LIST ; do
     if test ! -r $PSEUDO_DIR/$FILE ; then
@@ -120,9 +123,10 @@ EOF
 #
 $ECHO "  running the scf calculation...\c"
 $PW_COMMAND < ch4.scf.in > ch4.scf.out
+check_failure $?
 $ECHO " done"
 #
-# dynamic polarizability calculation 
+# dynamic polarizability calculation
 #
 cat > ch4.vdw.in << EOF
 
@@ -141,5 +145,8 @@ EOF
 #
 $ECHO "  running the dynamic polarizability calculation ...\c"
 $PH_COMMAND < ch4.vdw.in > ch4.vdw.out
+check_failure $?
 $ECHO " done"
 
+$ECHO
+$ECHO "$EXAMPLE_DIR : done"
