The check of output consistency is done on low-verbosity examples only. For high verbosity examples, daily_test checks the exit status of the relative run_example script. C.S.
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@3855 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/examples/daily_test b/examples/daily_test
--- a/examples/daily_test
+++ b/examples/daily_test
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # cp does not write the restart file to outdir but to the current directory.
-# All other restart files are either written to outdir and cleaned by this 
+# All other restart files are either written to outdir and cleaned by this
 # script or ignored, but if this is found the code will restart from last run
 /bin/rm -r /scr/giannozz/espresso/examples/example28/results/metadyn-cp_50.save/
 
@@ -66,7 +66,7 @@ if test "$conflicts" != "0" ; then
 fi
 changes=` grep -c -e '^U ' -e'^P ' cvs.log`
 if test  "$changes" = "0" ; then
-   # 
+   #
    # no changes to cvs, do nothing
    #
    exit 0
@@ -84,7 +84,7 @@ tail -1 config.log >> $OUT
 
 echo "#" >> $OUT
 echo "# MAKE ALL " >> $OUT
-echo "#" >> $OUT 
+echo "#" >> $OUT
 make all vib >& make.log
 errors=`grep -c -e Error make.log`
 if test  "$errors" = "0" ; then
@@ -114,22 +114,26 @@ echo > run.log
 #
 # TESTING ALL EXAMPLES
 #
-
 example_list=`/bin/ls -d example??`
 for example in $example_list
 do
 
     cd $PWROOT/examples/$example
+
     if test  "$example" = "example21" ; then
-    # the argument "64" to run_example is used in example 21
+       # the argument "64" to run_example is used in example 21
        ./run_example 64 >& run.log
     elif test  "$example" = "example26" ; then
-    # the arguments "1 7" to run_example are used in example 26
+       # the arguments "1 7" to run_example are used in example 26
        ./run_example 1 7 >& run.log
     else
-    # all other cases
+       # all other cases
        ./run_example >& run.log
     fi
+
+    # get the exit status of the script run_example
+    exit_status=$?
+
     cat run.log >> ../run.log
     /bin/rm run.log
     N=`echo $example | sed 's/example//'`
@@ -137,8 +141,17 @@ do
     echo "# CHECKING EXAMPLE # " $N >> $OUT
     echo "#" >> $OUT
 
-    ../check_example ./ >> $OUT
-
+    if /bin/grep "HIGH WERBOSITY EXAMPLE" < run_example > /dev/null ; then
+       # high verbosity example: check only exit status
+       if test $exit_status -eq 0; then
+          echo "exit status = $exit_status :  everything seems OK" >> $OUT
+       else
+          echo "exit status = $exit_status :  something went wrong" >> $OUT
+       fi
+    else
+       # low-verbosity example: do a full check
+       ../check_example ./ >> $OUT
+    fi
 done
 
 cd $PWROOT/examples
