adding a toplevel "make doc" to the daily test, which will help enforce the good state of *.def and *.tex files
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@5710 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/examples/daily_test b/examples/daily_test
--- a/examples/daily_test
+++ b/examples/daily_test
@@ -188,4 +188,20 @@ else
 #
 fi
 #
+
+echo "#" >> $OUT
+echo "# MAKE DOC " >> $OUT
+echo "#" >> $OUT
+make doc >& make.log
+errors=`grep -c -e Error make.log`
+if test  "$errors" = "0" ; then
+   echo "make doc: success" >> $OUT
+else
+   echo "make doc: failure! Last 50 lines from 'make all':" >> $OUT
+   echo "-------------------------------------------------" >> $OUT
+   tail -50 make.log >>  $OUT
+   mail -s "RESULTS OF DAILY QE TEST" $MAILTO < $OUT
+   exit $errors
+fi
+
 mail -s "RESULTS OF DAILY QE TEST" $MAILTO < $OUT
