An attempt to have SP recognize scalapack
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@8386 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/install/configure b/install/configure
--- a/install/configure
+++ b/install/configure
@@ -10087,7 +10087,81 @@ if test "$ac_res" != no; then
 fi
 
        test "$have_scalapack" -eq 1 && break
-# scalapack + blacs
+# scalapack + blacs, no -L options
+       unset ac_cv_search_pdgemr2d # clear cached value
+       blacs_libs="-lblacs -lblacsF77init -lblacs"
+       scalapack_libs="-lscalapack $blacs_libs"
+       LIBS="$mpi_libs $scalapack_libs"
+       LDFLAGS=""
+       { echo "$as_me:$LINENO: checking for library containing pdgemr2d" >&5
+echo $ECHO_N "checking for library containing pdgemr2d... $ECHO_C" >&6; }
+if test "${ac_cv_search_pdgemr2d+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call pdgemr2d
+      end
+_ACEOF
+for ac_lib in '' "" ; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_f77_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_search_pdgemr2d=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_pdgemr2d+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_pdgemr2d+set}" = set; then
+  :
+else
+  ac_cv_search_pdgemr2d=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_pdgemr2d" >&5
+echo "${ECHO_T}$ac_cv_search_pdgemr2d" >&6; }
+ac_res=$ac_cv_search_pdgemr2d
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+  have_scalapack=1
+                   try_dflags="$try_dflags -D__SCALAPACK"
+fi
+
+       test "$have_scalapack" -eq 1 && break
+# scalapack + blacs with -L options
        unset ac_cv_search_pdgemr2d # clear cached value
        if test "$scalapack_dir" = ""; then scalapack_dir="/bgsys/local/scalapack/lib"; fi
        if test "$blacs_dir" = ""; then blacs_dir="/bgsys/local/blacs/lib"; fi
