preparing plugin makefile for sax. PLUMED now also download from qe-forge
git-svn-id: http://qeforge.qe-forge.org/svn/q-e/trunk/espresso@8900 c92efa57-630b-4861-b058-cf58834340f0

diff --git a/install/plugins_makefile b/install/plugins_makefile
--- a/install/plugins_makefile
+++ b/install/plugins_makefile
@@ -8,8 +8,6 @@
 
 include ../make.sys
 include plugins_list
-PLUMED=PLUMED-latest
-GIPAW=qe-gipaw-latest
 #
 # MAIN target
 #
@@ -24,16 +22,16 @@ gipaw:  uncompress-gipaw configure-gipaw
 	cd ../GIPAW; $(MAKE) all; cd ../bin; ln -fs ../GIPAW/bin/gipaw.x . ; fi
 	touch make-gipaw
 uncompress-gipaw: touch-dummy
-	@(if test ! -e ../archive/qe-gipaw-latest.tar.gz && test ! -d ../GIPAW ; then \
-	wget -O ../archive/qe-gipaw-latest.tar.gz http://qe-forge.org/frs/download.php/166/qe-gipaw-latest.tar.gz > /dev/null 2>&1; \
+	@(if test ! -e ../archive/$(GIPAW).tar.gz && test ! -d ../GIPAW ; then \
+	wget -O ../archive/$(GIPAW).tar.gz $(GIPAW_URL) > /dev/null 2>&1; \
 	if test "`echo $$?`" -ne "0" ; then \
-	curl -o ../archive/qe-gipaw-latest.tar.gz http://qe-forge.org/frs/download.php/166/qe-gipaw-latest.tar.gz > /dev/null 2>&1; \
+	curl -o ../archive/$(GIPAW).tar.gz $(GIPAW_URL) > /dev/null 2>&1; \
 	if test "`echo $$?`" -ne "0" ; then \
 	echo "unable to download qe-gipaw. Test whether curl or wget is installed in your computer." ; \
 	fi ; fi ; fi) 
 	if test ! -d ../GIPAW; then \
-	(gzip -dc ../archive/qe-gipaw-latest.tar.gz | (cd ../ ; tar -xvf -)) ; \
-	(cd ../ ; ln -s qe-gipaw* GIPAW) ; fi 
+	(gzip -dc ../archive/$(GIPAW).tar.gz | (cd ../ ; tar -xvf -)) ; \
+	(cd ../ ; ln -s $(GIPAW) GIPAW) ; fi 
 	touch uncompress-gipaw
 configure-gipaw: touch-dummy
 	cd ../GIPAW ; \
@@ -167,19 +165,75 @@ plumed: test-plumed uncompress-plumed patch-plumed
 	touch make-plumed
 test-plumed: touch-dummy
 	@(if test ! -e ../archive/$(PLUMED).tar.gz && test ! -d ../PLUMED; then \
-	echo "The release contains no PLUMED package"; fi) 
+	echo "The release contains no PLUMED package. Trying to download it from qe-forge."; fi) 
 	touch ./test-plumed
 uncompress-plumed: touch-dummy
-	if (test -e archive/$(PLUMED).tar.gz) || (test ! -d ../PLUMED); then \
-	( gzip -dc ../archive/$(PLUMED).tar.gz | (cd ../; tar -xvf -)) ; \
-	( mv ../PLUMED-latest ../PLUMED) ; fi
-	touch ./uncompress-plumed
+	@(if test ! -e ../archive/$(PLUMED).tar.gz && test ! -d ../PLUMED ; then \
+	wget -O ../archive/$(PLUMED).tar.gz $(PLUMED_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(PLUMED).tar.gz $(PLUMED_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download plumed. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../PLUMED; then \
+	(gzip -dc ../archive/$(PLUMED).tar.gz | (cd ../ ; tar -xvf -)) ; \
+	(cd ../ ; ln -s $(PLUMED) PLUMED) ; fi 
+	touch uncompress-yambo
+
 patch-plumed: touch-dummy
 	if test -d ../PLUMED; then \
 	(cd ../PLUMED ; export plumedir="`pwd`" ; \
 	cp  patches/plumedpatch_qespresso.sh ../ ; \
 	cd ../ ; ./plumedpatch_qespresso.sh -patch) ; fi	
 	touch ./patch-plumed
+
+##################################
+# SaX
+##################################
+
+sax: extlibs uncompress-sax configure-sax
+	if test -d ../SaX; then \
+	cd ../SaX; $(MAKE) sax_all; fi
+#	- ( cd ../bin ; ln -sf ../SaX/sax/bin/* . ) 
+	touch ./make-want
+uncompress-sax: touch-dummy
+	@(if test ! -e ../archive/$(SAX).tar.gz && test ! -d ../SaX ; then \
+	wget -O ../archive/$(SAX).tar.gz $(SAX_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(SAX).tar.gz $(SAX_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download want. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../SaX; then \
+	(gzip -dc ../archive/$(SAX).tar.gz | (cd ../ ; tar -xvf -)) ; \
+	(cd ../ ; ln -s $(SAX) SaX) ; fi 
+	touch uncompress-sax
+
+configure-sax: touch-dummy
+	cd ../SaX ; \
+	./configure \
+	--with-external-iotk \
+	IOTK_LIBS="-L../../S3DE/iotk/src -liotk" \
+	IOTK_INCLUDE="$(MOD_FLAG)../../S3DE/iotk/src" \
+	CC="$(CC)" \
+	F90="$(F90)" \
+	MPIF90="$(MPIF90)" \
+	F90FLAGS="$(F90FLAGS) $($PRE_FDFLAGS) $(FDFLAGS) $(IFLAGS) $(MODFLAGS)" \
+	F77="$(F77)" \
+	FFLAGS="$(FFLAGS)" \
+	FFLAGS_NOOPT="$(FFLAGS_NOOPT)" \
+	LD="$(LD)" \
+	LDFLAGS="$(LDFLAGS)" \
+	AR="$(AR)" \
+	ARFLAGS="$(ARFLAGS)" \
+	RANLIB="$(RANLIB)" \
+	DFLAGS="$(DFLAGS)" \
+	FDFLAGS="$(DFLAGS)" \
+	LAPACK_LIBS="$(LAPACK_LIBS)" \
+	BLAS_LIBS="$(BLAS_LIBS)" \
+	FFT_LIBS="$(FFT_LIBS)" 
+	touch ./configure-sax
+
 
 ##################################
 # extlibs
@@ -215,7 +269,7 @@ w90_veryclean: w90_clean
 	if test -d ../W90; then (rm -R -f ../W90); fi
 	if test -d ../$(W90); then (rm -R -f ../$(W90)); fi
 	rm -f ../bin/wannier90.x
-	rm -rf ./make-w90 ./configure-w90 ./uncompress-w90
+	rm -rf ./uncompress-w90
 want_clean:
 	if test -d ../WANT; then (cd ../WANT; \
 	$(MAKE) clean); fi
@@ -224,7 +278,7 @@ want_clean:
 want_veryclean: want_clean
 	if test -d ../WANT; then (rm -R -f ../WANT); fi
 	if test -d ../$(WANT); then (rm -R -f ../$(WANT)); fi
-	- rm -rf ./make-want ./configure-want ./uncompress-want
+	- rm -rf ./uncompress-want
 yambo_clean:
 	if test -d ../YAMBO; then (cd ../YAMBO; \
 	$(MAKE) clean); fi
@@ -233,16 +287,29 @@ yambo_clean:
 yambo_veryclean: yambo_clean
 	if test -d ../YAMBO; then (rm -R -f ../YAMBO); fi
 	if test -d ../$(YAMBO); then (rm -R -f ../$(YAMBO)); fi
-	- rm -rf ./make-yambo ./configure-yambo ./uncompress-yambo
+	- rm -rf ./uncompress-yambo
+
 plumed_clean:
 	if test -d ../PLUMED; then (cd ../PLUMED; \
 	export plumedir="`pwd`" ; \
 	cd ../ ; ./plumedpatch_qespresso.sh -revert); fi
 	cd ../PW ; $(MAKE) clean; cd ../CPV ; $(MAKE) clean
 	rm -rf ./make-plumed ./patch-plumed
+
 plumed_veryclean: plumed_clean
 	if test -d ../PLUMED; then (rm -R -f ../PLUMED); fi
+	if test -d ../$(PLUMED); then (rm -R -f ../$(PLUMED)); fi
 	rm -rf ./uncompress-plumed ../plumedpatch_qespresso.sh
+
+sax_clean:
+	if test -d ../SaX; then (cd ../SaX; \
+	$(MAKE) clean); fi
+	- rm -rf ./make-sax ./configure-sax
+
+sax_veryclean: sax_clean
+	if test -d ../SaX; then (rm -R -f ../SaX); fi
+	if test -d ../$(SAX); then (rm -R -f ../$(SAX)); fi
+	- rm -rf ./uncompress-sax
 
 ##########################################################
 # general cleaning
