Modifications in TDDFPT and HP modules: 1) Remove PP files from examples of TDDFPT, use an automatic download of PPs from the QE web site; 2) TDDFPT examples are now in the standard format of QE (using run_example scripts); 3) Fix the bug in TDDFPT+EXX due to recent changes in PW (fft_fact); 4) The ecutfock parameter in TDDFPT+EXX is now read from XML and cannot be specified from the input of TDDFPT; 5) In TDDFPT the oscillator strength (absorption coefficient) is now written in a separate file (and not in the same file where \chi is written); 6) HP examples use PPs from the Pslibrary by an automatic download from the QE website.

diff --git a/HP/examples/example02/run_example b/HP/examples/example02/run_example
--- a/HP/examples/example02/run_example
+++ b/HP/examples/example02/run_example
@@ -14,11 +14,11 @@ $ECHO "This example shows how to use pw.x and hp.x to calculate"
 $ECHO "the Hubbard U parameter for Ni in NiO."
 
 # set the needed environment variables
-. ../environment_variables
+. ../../../environment_variables
 
 # required executables and pseudopotentials
 BIN_LIST="pw.x hp.x"
-PSEUDO_LIST="ni_pbesol_v1.4.uspp.F.UPF O.pbesol-n-kjpaw_psl.0.1.UPF"
+PSEUDO_LIST="Ni.pbesol-n-rrkjus_psl.0.1.UPF O.pbesol-n-rrkjus_psl.0.1.UPF"
 
 $ECHO
 $ECHO "  executables directory: $BIN_DIR"
@@ -26,10 +26,6 @@ $ECHO "  pseudo directory:      $PSEUDO_DIR"
 $ECHO "  temporary directory:   $TMP_DIR"
 $ECHO
 $ECHO "  checking that needed directories and files exist...\c"
-$ECHO
-$ECHO " Pseudopotentials were selected from the SSSP library:"
-$ECHO " https://www.materialscloud.org/discover/sssp/table/precision\c"
-$ECHO
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
@@ -52,6 +48,22 @@ for FILE in $BIN_LIST ; do
     if test ! -x $BIN_DIR/$FILE ; then
         $ECHO
         $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
+        $ECHO "Aborting"
+        exit 1
+    fi
+done
+$ECHO " done"
+
+# check for pseudopotentials
+for FILE in $PSEUDO_LIST ; do
+    if test ! -r $PSEUDO_DIR/$FILE ; then
+       $ECHO
+       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
+            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
+    fi
+    if test $? != 0; then
+        $ECHO
+        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
         $ECHO "Aborting"
         exit 1
     fi
@@ -107,9 +119,9 @@ cat > $PREFIX.scf1.in << EOF
     mixing_beta = 0.7
  /
 ATOMIC_SPECIES
- Ni1  58.693  ni_pbesol_v1.4.uspp.F.UPF
- Ni2  58.693  ni_pbesol_v1.4.uspp.F.UPF
- O    16.000  O.pbesol-n-kjpaw_psl.0.1.UPF
+ Ni1  58.693  Ni.pbesol-n-rrkjus_psl.0.1.UPF
+ Ni2  58.693  Ni.pbesol-n-rrkjus_psl.0.1.UPF
+ O    16.000  O.pbesol-n-rrkjus_psl.0.1.UPF
 ATOMIC_POSITIONS {alat}
  Ni1  0.0000000   0.0000000   0.0000000
  Ni2  0.5000000   0.5000000   0.0000000
@@ -123,7 +135,7 @@ K_POINTS {automatic}
  2 2 2 0 0 0
 EOF
 $ECHO "  Running the SCF calculation for $PREFIX..."
-$PW_COMMAND < $PREFIX.scf1.in |tee $PREFIX.scf1.out
+$PW_COMMAND < $PREFIX.scf1.in > $PREFIX.scf1.out
 $ECHO " done"
 
 # Extract the number of Kohn-Sham states from the previous run
@@ -166,9 +178,9 @@ cat > $PREFIX.scf2.in << EOF
     startingwfc = 'file'
  /
 ATOMIC_SPECIES
- Ni1  58.693  ni_pbesol_v1.4.uspp.F.UPF
- Ni2  58.693  ni_pbesol_v1.4.uspp.F.UPF
- O    16.000  O.pbesol-n-kjpaw_psl.0.1.UPF
+ Ni1  58.693  Ni.pbesol-n-rrkjus_psl.0.1.UPF
+ Ni2  58.693  Ni.pbesol-n-rrkjus_psl.0.1.UPF
+ O    16.000  O.pbesol-n-rrkjus_psl.0.1.UPF
 ATOMIC_POSITIONS {alat}
  Ni1  0.0000000   0.0000000   0.0000000
  Ni2  0.5000000   0.5000000   0.0000000
@@ -182,8 +194,9 @@ K_POINTS {automatic}
  2 2 2 0 0 0
 EOF
 $ECHO "  Running the SCF calculation for $PREFIX..."
-$PW_COMMAND < $PREFIX.scf2.in |tee $PREFIX.scf2.out
+$PW_COMMAND < $PREFIX.scf2.in > $PREFIX.scf2.out
 $ECHO " done"
+
 
 # Perform the linear-response calculation
 cat > $PREFIX.hp.in << EOF
@@ -196,5 +209,5 @@ cat > $PREFIX.hp.in << EOF
  /
 EOF
 $ECHO "  Running the linear-response calculation of Hubbard U..."
-$HP_COMMAND < $PREFIX.hp.in |tee $PREFIX.hp.out
+$HP_COMMAND < $PREFIX.hp.in > $PREFIX.hp.out
 $ECHO " done"
diff --git a/HP/examples/example08/run_example b/HP/examples/example08/run_example
--- a/HP/examples/example08/run_example
+++ b/HP/examples/example08/run_example
@@ -14,11 +14,11 @@ $ECHO "This example shows how to use pw.x and hp.x to calculate"
 $ECHO "the Hubbard U parameters for Ni in NiO2 (2D system)."
 
 # set the needed environment variables
-. ../environment_variables
+. ../../../environment_variables
 
 # required executables and pseudopotentials
 BIN_LIST="pw.x hp.x"
-PSEUDO_LIST="ni_pbe_v1.4.uspp.F.UPF O.pbe-n-kjpaw_psl.0.1.UPF"
+PSEUDO_LIST="Ni.pbe-n-rrkjus_psl.0.1.UPF O.pbe-n-rrkjus_psl.0.1.UPF"
 
 $ECHO
 $ECHO "  executables directory: $BIN_DIR"
@@ -26,10 +26,6 @@ $ECHO "  pseudo directory:      $PSEUDO_DIR"
 $ECHO "  temporary directory:   $TMP_DIR"
 $ECHO
 $ECHO "  checking that needed directories and files exist...\c"
-$ECHO
-$ECHO " Pseudopotentials were selected from the SSSP library:"
-$ECHO " https://www.materialscloud.org/discover/sssp/table/precision\c"
-$ECHO
 
 # check for directories
 for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
@@ -52,6 +48,22 @@ for FILE in $BIN_LIST ; do
     if test ! -x $BIN_DIR/$FILE ; then
         $ECHO
         $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
+        $ECHO "Aborting"
+        exit 1
+    fi
+done
+$ECHO " done"
+
+# check for pseudopotentials
+for FILE in $PSEUDO_LIST ; do
+    if test ! -r $PSEUDO_DIR/$FILE ; then
+       $ECHO
+       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
+            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
+    fi
+    if test $? != 0; then
+        $ECHO
+        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
         $ECHO "Aborting"
         exit 1
     fi
@@ -99,8 +111,8 @@ cat > $PREFIX.scf.in << EOF
     mixing_beta = 0.3
  /
 ATOMIC_SPECIES
-Ni   58.6934  ni_pbe_v1.4.uspp.F.UPF
-O    15.9994  O.pbe-n-kjpaw_psl.0.1.UPF
+Ni   58.6934  Ni.pbe-n-rrkjus_psl.0.1.UPF
+O    15.9994  O.pbe-n-rrkjus_psl.0.1.UPF
 ATOMIC_POSITIONS {angstrom}
 Ni   0.0000000000    0.0000000000    10.9412265283
 O    1.4121016725    0.8152772808    10.0006291225
@@ -113,7 +125,7 @@ K_POINTS {automatic}
  4 4 1 0 0 0
 EOF
 $ECHO "  Running the SCF calculation for $PREFIX..."
-$PW_COMMAND < $PREFIX.scf.in |tee $PREFIX.scf.out
+$PW_COMMAND < $PREFIX.scf.in > $PREFIX.scf.out
 $ECHO " done"
 
 
@@ -128,5 +140,5 @@ cat > $PREFIX.hp.in << EOF
  /
 EOF
 $ECHO "  Running the linear-response calculation of Hubbard U..."
-$HP_COMMAND < $PREFIX.hp.in |tee $PREFIX.hp.out
+$HP_COMMAND < $PREFIX.hp.in > $PREFIX.hp.out
 $ECHO " done"
